# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_user_profile200_response_specifics_all_of_any_of_projects_inner import GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner

class TestGetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner(unittest.TestCase):
    """GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner:
        """Test GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner`
        """
        model = GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner()
        if include_optional:
            return GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner(
                name = '',
                description = '',
                contributors = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_projects_inner_contributors_inner.getUserProfile_200_response_specifics_allOf_anyOf_projects_inner_contributors_inner(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', )
                    ],
                skills = [
                    ''
                    ],
                skills_preview = '',
                started_on = '',
                ended_on = ''
            )
        else:
            return GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner(
                name = '',
                contributors = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_projects_inner_contributors_inner.getUserProfile_200_response_specifics_allOf_anyOf_projects_inner_contributors_inner(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', )
                    ],
        )
        """

    def testGetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner(self):
        """Test GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
