# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_classic_job_posting200_response_budget_total import GetClassicJobPosting200ResponseBudgetTotal

class TestGetClassicJobPosting200ResponseBudgetTotal(unittest.TestCase):
    """GetClassicJobPosting200ResponseBudgetTotal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClassicJobPosting200ResponseBudgetTotal:
        """Test GetClassicJobPosting200ResponseBudgetTotal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClassicJobPosting200ResponseBudgetTotal`
        """
        model = GetClassicJobPosting200ResponseBudgetTotal()
        if include_optional:
            return GetClassicJobPosting200ResponseBudgetTotal(
                amount = 1.337,
                currency = ''
            )
        else:
            return GetClassicJobPosting200ResponseBudgetTotal(
                amount = 1.337,
                currency = '',
        )
        """

    def testGetClassicJobPosting200ResponseBudgetTotal(self):
        """Test GetClassicJobPosting200ResponseBudgetTotal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
