# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in_education_inner_school import LinkedInEducationInnerSchool

class TestLinkedInEducationInnerSchool(unittest.TestCase):
    """LinkedInEducationInnerSchool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedInEducationInnerSchool:
        """Test LinkedInEducationInnerSchool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedInEducationInnerSchool`
        """
        model = LinkedInEducationInnerSchool()
        if include_optional:
            return LinkedInEducationInnerSchool(
                id = '',
                name = '',
                picture_url = '',
                profile_url = ''
            )
        else:
            return LinkedInEducationInnerSchool(
                id = '',
        )
        """

    def testLinkedInEducationInnerSchool(self):
        """Test LinkedInEducationInnerSchool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
