# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.set_presence200_response import SetPresence200Response

class TestSetPresence200Response(unittest.TestCase):
    """SetPresence200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetPresence200Response:
        """Test SetPresence200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetPresence200Response`
        """
        model = SetPresence200Response()
        if include_optional:
            return SetPresence200Response(
                object = 'PresenceSet'
            )
        else:
            return SetPresence200Response(
                object = 'PresenceSet',
        )
        """

    def testSetPresence200Response(self):
        """Test SetPresence200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
