# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.list_webhook_endpoints200_response_data_inner import ListWebhookEndpoints200ResponseDataInner

class TestListWebhookEndpoints200ResponseDataInner(unittest.TestCase):
    """ListWebhookEndpoints200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWebhookEndpoints200ResponseDataInner:
        """Test ListWebhookEndpoints200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWebhookEndpoints200ResponseDataInner`
        """
        model = ListWebhookEndpoints200ResponseDataInner()
        if include_optional:
            return ListWebhookEndpoints200ResponseDataInner(
                enabled = True,
                description = '',
                url = '',
                trigger_events = [
                    'account.status.disconnected'
                    ],
                secret = '',
                object = 'WebhookEndpoint',
                id = 'we_jUR,rZ#UM/?R,Fp^l6$ARj',
                application_id = 'app_jUR,rZ#UM/?R,Fp^l6$ARj',
                account_ids = [
                    'acc_jUR,rZ#UM/?R,Fp^l6$ARj'
                    ],
                account_targets = [
                    unipile.models.list_webhook_endpoints_200_response_data_inner_account_targets_inner.listWebhookEndpoints_200_response_data_inner_account_targets_inner(
                        account_name = '', 
                        account_provider = 'mock', 
                        object = 'WebhookEndpointAccountTarget', 
                        id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj', 
                        status = 'active', )
                    ]
            )
        else:
            return ListWebhookEndpoints200ResponseDataInner(
                enabled = True,
                description = '',
                url = '',
                trigger_events = [
                    'account.status.disconnected'
                    ],
                secret = '',
                object = 'WebhookEndpoint',
                id = 'we_jUR,rZ#UM/?R,Fp^l6$ARj',
                application_id = 'app_jUR,rZ#UM/?R,Fp^l6$ARj',
                account_ids = [
                    'acc_jUR,rZ#UM/?R,Fp^l6$ARj'
                    ],
                account_targets = [
                    unipile.models.list_webhook_endpoints_200_response_data_inner_account_targets_inner.listWebhookEndpoints_200_response_data_inner_account_targets_inner(
                        account_name = '', 
                        account_provider = 'mock', 
                        object = 'WebhookEndpointAccountTarget', 
                        id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj', 
                        status = 'active', )
                    ],
        )
        """

    def testListWebhookEndpoints200ResponseDataInner(self):
        """Test ListWebhookEndpoints200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
