# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.26.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.update_chat200_response_participants_inner_user import UpdateChat200ResponseParticipantsInnerUser

class TestUpdateChat200ResponseParticipantsInnerUser(unittest.TestCase):
    """UpdateChat200ResponseParticipantsInnerUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateChat200ResponseParticipantsInnerUser:
        """Test UpdateChat200ResponseParticipantsInnerUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateChat200ResponseParticipantsInnerUser`
        """
        model = UpdateChat200ResponseParticipantsInnerUser()
        if include_optional:
            return UpdateChat200ResponseParticipantsInnerUser(
                id = '',
                object = 'User',
                type = 'individual',
                public_identifier = '',
                display_name = '',
                first_name = '',
                last_name = '',
                profile_url = '',
                public_picture_url = '',
                private_picture_download_url = '',
                description = '',
                specifics = None
            )
        else:
            return UpdateChat200ResponseParticipantsInnerUser(
                id = '',
                object = 'User',
                type = 'individual',
                display_name = '',
        )
        """

    def testUpdateChat200ResponseParticipantsInnerUser(self):
        """Test UpdateChat200ResponseParticipantsInnerUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
