# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_posts_list200_response_data_inner_reposted_by import GetPostsList200ResponseDataInnerRepostedBy

class TestGetPostsList200ResponseDataInnerRepostedBy(unittest.TestCase):
    """GetPostsList200ResponseDataInnerRepostedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPostsList200ResponseDataInnerRepostedBy:
        """Test GetPostsList200ResponseDataInnerRepostedBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPostsList200ResponseDataInnerRepostedBy`
        """
        model = GetPostsList200ResponseDataInnerRepostedBy()
        if include_optional:
            return GetPostsList200ResponseDataInnerRepostedBy(
                id = '',
                object = 'User',
                type = 'individual',
                public_identifier = '',
                display_name = '',
                profile_url = '',
                public_picture_url = '',
                private_picture_download_url = '',
                description = ''
            )
        else:
            return GetPostsList200ResponseDataInnerRepostedBy(
                id = '',
                object = 'User',
                type = 'individual',
                display_name = '',
        )
        """

    def testGetPostsList200ResponseDataInnerRepostedBy(self):
        """Test GetPostsList200ResponseDataInnerRepostedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
