# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.update_draft_request_specifics import UpdateDraftRequestSpecifics

class TestUpdateDraftRequestSpecifics(unittest.TestCase):
    """UpdateDraftRequestSpecifics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDraftRequestSpecifics:
        """Test UpdateDraftRequestSpecifics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDraftRequestSpecifics`
        """
        model = UpdateDraftRequestSpecifics()
        if include_optional:
            return UpdateDraftRequestSpecifics(
                outlook = unipile.models.update_draft_request_specifics_all_of_outlook.updateDraft_request_specifics_allOf_outlook(
                    categories = [
                        ''
                        ], )
            )
        else:
            return UpdateDraftRequestSpecifics(
        )
        """

    def testUpdateDraftRequestSpecifics(self):
        """Test UpdateDraftRequestSpecifics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
