# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.create_new_education_degree import CreateNewEducationDegree

class TestCreateNewEducationDegree(unittest.TestCase):
    """CreateNewEducationDegree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateNewEducationDegree:
        """Test CreateNewEducationDegree
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateNewEducationDegree`
        """
        model = CreateNewEducationDegree()
        if include_optional:
            return CreateNewEducationDegree(
                name = '',
                id = ''
            )
        else:
            return CreateNewEducationDegree(
                name = '',
        )
        """

    def testCreateNewEducationDegree(self):
        """Test CreateNewEducationDegree"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
