# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_classic_company_profile200_response_mailbox import GetClassicCompanyProfile200ResponseMailbox

class TestGetClassicCompanyProfile200ResponseMailbox(unittest.TestCase):
    """GetClassicCompanyProfile200ResponseMailbox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClassicCompanyProfile200ResponseMailbox:
        """Test GetClassicCompanyProfile200ResponseMailbox
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClassicCompanyProfile200ResponseMailbox`
        """
        model = GetClassicCompanyProfile200ResponseMailbox()
        if include_optional:
            return GetClassicCompanyProfile200ResponseMailbox(
                id = '',
                enabled = True
            )
        else:
            return GetClassicCompanyProfile200ResponseMailbox(
                id = '',
                enabled = True,
        )
        """

    def testGetClassicCompanyProfile200ResponseMailbox(self):
        """Test GetClassicCompanyProfile200ResponseMailbox"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
