# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.trash_email200_response import TrashEmail200Response

class TestTrashEmail200Response(unittest.TestCase):
    """TrashEmail200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrashEmail200Response:
        """Test TrashEmail200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrashEmail200Response`
        """
        model = TrashEmail200Response()
        if include_optional:
            return TrashEmail200Response(
                object = 'EmailTrashed'
            )
        else:
            return TrashEmail200Response(
                object = 'EmailTrashed',
        )
        """

    def testTrashEmail200Response(self):
        """Test TrashEmail200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
