# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.publish_in_promoted_mode1_budget import PublishInPromotedMode1Budget

class TestPublishInPromotedMode1Budget(unittest.TestCase):
    """PublishInPromotedMode1Budget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishInPromotedMode1Budget:
        """Test PublishInPromotedMode1Budget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishInPromotedMode1Budget`
        """
        model = PublishInPromotedMode1Budget()
        if include_optional:
            return PublishInPromotedMode1Budget(
                currency = '012',
                amount = 1.337,
                scope = 'DAILY'
            )
        else:
            return PublishInPromotedMode1Budget(
                currency = '012',
                amount = 1.337,
                scope = 'DAILY',
        )
        """

    def testPublishInPromotedMode1Budget(self):
        """Test PublishInPromotedMode1Budget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
