# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_messages_list200_response_data_inner_event_metadata_any_of1 import GetMessagesList200ResponseDataInnerEventMetadataAnyOf1

class TestGetMessagesList200ResponseDataInnerEventMetadataAnyOf1(unittest.TestCase):
    """GetMessagesList200ResponseDataInnerEventMetadataAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMessagesList200ResponseDataInnerEventMetadataAnyOf1:
        """Test GetMessagesList200ResponseDataInnerEventMetadataAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMessagesList200ResponseDataInnerEventMetadataAnyOf1`
        """
        model = GetMessagesList200ResponseDataInnerEventMetadataAnyOf1()
        if include_optional:
            return GetMessagesList200ResponseDataInnerEventMetadataAnyOf1(
                description = ''
            )
        else:
            return GetMessagesList200ResponseDataInnerEventMetadataAnyOf1(
        )
        """

    def testGetMessagesList200ResponseDataInnerEventMetadataAnyOf1(self):
        """Test GetMessagesList200ResponseDataInnerEventMetadataAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
