# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.45.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.telegram1_config import Telegram1Config

class TestTelegram1Config(unittest.TestCase):
    """Telegram1Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Telegram1Config:
        """Test Telegram1Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Telegram1Config`
        """
        model = Telegram1Config()
        if include_optional:
            return Telegram1Config(
                custom_proxy = unipile.models.custom_proxy.Custom proxy(
                    host = '', 
                    port = 1.337, 
                    username = '', 
                    password = '', 
                    protocol = 'https', )
            )
        else:
            return Telegram1Config(
        )
        """

    def testTelegram1Config(self):
        """Test Telegram1Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
