# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.proxy_request_request import ProxyRequestRequest

class TestProxyRequestRequest(unittest.TestCase):
    """ProxyRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProxyRequestRequest:
        """Test ProxyRequestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProxyRequestRequest`
        """
        model = ProxyRequestRequest()
        if include_optional:
            return ProxyRequestRequest(
                url = '',
                method = 'GET',
                body = {
                    'key' : null
                    },
                headers = {
                    'key' : ''
                    },
                path_variables = {
                    'key' : ''
                    },
                var_query_params = {
                    'key' : ''
                    },
                bypass_url_encoding = True
            )
        else:
            return ProxyRequestRequest(
                url = '',
                method = 'GET',
        )
        """

    def testProxyRequestRequest(self):
        """Test ProxyRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
