# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.full_profile_projects_inner import FullProfileProjectsInner

class TestFullProfileProjectsInner(unittest.TestCase):
    """FullProfileProjectsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullProfileProjectsInner:
        """Test FullProfileProjectsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullProfileProjectsInner`
        """
        model = FullProfileProjectsInner()
        if include_optional:
            return FullProfileProjectsInner(
                name = '',
                description = '',
                contributors = [
                    unipile.models.linked_in_projects_inner_contributors_inner.LinkedIn_projects_inner_contributors_inner(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', )
                    ],
                skills = [
                    ''
                    ],
                skills_preview = '',
                started_on = '',
                ended_on = ''
            )
        else:
            return FullProfileProjectsInner(
                name = '',
                contributors = [
                    unipile.models.linked_in_projects_inner_contributors_inner.LinkedIn_projects_inner_contributors_inner(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', )
                    ],
        )
        """

    def testFullProfileProjectsInner(self):
        """Test FullProfileProjectsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
