# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.send_email_request_tracking_options import SendEmailRequestTrackingOptions

class TestSendEmailRequestTrackingOptions(unittest.TestCase):
    """SendEmailRequestTrackingOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailRequestTrackingOptions:
        """Test SendEmailRequestTrackingOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailRequestTrackingOptions`
        """
        model = SendEmailRequestTrackingOptions()
        if include_optional:
            return SendEmailRequestTrackingOptions(
                opens = True,
                links = True,
                label = '',
                custom_domain = ''
            )
        else:
            return SendEmailRequestTrackingOptions(
        )
        """

    def testSendEmailRequestTrackingOptions(self):
        """Test SendEmailRequestTrackingOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
