# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in_recommendations_received_inner import LinkedInRecommendationsReceivedInner

class TestLinkedInRecommendationsReceivedInner(unittest.TestCase):
    """LinkedInRecommendationsReceivedInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedInRecommendationsReceivedInner:
        """Test LinkedInRecommendationsReceivedInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedInRecommendationsReceivedInner`
        """
        model = LinkedInRecommendationsReceivedInner()
        if include_optional:
            return LinkedInRecommendationsReceivedInner(
                caption = '',
                created_on = '',
                text = '',
                user = unipile.models.linked_in_recommendations_received_inner_user.LinkedIn_recommendations_received_inner_user(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', )
            )
        else:
            return LinkedInRecommendationsReceivedInner(
                text = '',
                user = unipile.models.linked_in_recommendations_received_inner_user.LinkedIn_recommendations_received_inner_user(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', ),
        )
        """

    def testLinkedInRecommendationsReceivedInner(self):
        """Test LinkedInRecommendationsReceivedInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
