# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.new_experience_skills_inner import NewExperienceSkillsInner

class TestNewExperienceSkillsInner(unittest.TestCase):
    """NewExperienceSkillsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewExperienceSkillsInner:
        """Test NewExperienceSkillsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewExperienceSkillsInner`
        """
        model = NewExperienceSkillsInner()
        if include_optional:
            return NewExperienceSkillsInner(
                text = '',
                id = '4'
            )
        else:
            return NewExperienceSkillsInner(
                text = '',
        )
        """

    def testNewExperienceSkillsInner(self):
        """Test NewExperienceSkillsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
