# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_classic_applicants200_response_data_inner_profile import GetClassicApplicants200ResponseDataInnerProfile

class TestGetClassicApplicants200ResponseDataInnerProfile(unittest.TestCase):
    """GetClassicApplicants200ResponseDataInnerProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClassicApplicants200ResponseDataInnerProfile:
        """Test GetClassicApplicants200ResponseDataInnerProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClassicApplicants200ResponseDataInnerProfile`
        """
        model = GetClassicApplicants200ResponseDataInnerProfile()
        if include_optional:
            return GetClassicApplicants200ResponseDataInnerProfile(
                id = '',
                display_name = '',
                headline = '',
                public_identifier = '',
                location = '',
                network_distance = 'SELF',
                profile_url = '',
                public_picture_url = '',
                work_experience = [
                    unipile.models.get_classic_applicants_200_response_data_inner_profile_work_experience_inner.getClassicApplicants_200_response_data_inner_profile_work_experience_inner(
                        company = unipile.models.linked_in_certifications_inner_organization.LinkedIn_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        title = '', 
                        started_on = '', 
                        ended_on = '', 
                        location = '', 
                        description = '', 
                        employment_type = '', )
                    ],
                educations = [
                    unipile.models.get_classic_applicants_200_response_data_inner_profile_educations_inner.getClassicApplicants_200_response_data_inner_profile_educations_inner(
                        school = unipile.models.get_classic_applicants_200_response_data_inner_profile_educations_inner_school.getClassicApplicants_200_response_data_inner_profile_educations_inner_school(
                            id = '', 
                            name = '', 
                            picture_url = '', 
                            profile_url = '', ), 
                        degree = '', 
                        description = '', 
                        field_of_study = '', 
                        grade = '', 
                        started_on = '', 
                        ended_on = '', )
                    ]
            )
        else:
            return GetClassicApplicants200ResponseDataInnerProfile(
                id = '',
                display_name = '',
                headline = '',
                location = '',
                network_distance = 'SELF',
                profile_url = '',
                work_experience = [
                    unipile.models.get_classic_applicants_200_response_data_inner_profile_work_experience_inner.getClassicApplicants_200_response_data_inner_profile_work_experience_inner(
                        company = unipile.models.linked_in_certifications_inner_organization.LinkedIn_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        title = '', 
                        started_on = '', 
                        ended_on = '', 
                        location = '', 
                        description = '', 
                        employment_type = '', )
                    ],
                educations = [
                    unipile.models.get_classic_applicants_200_response_data_inner_profile_educations_inner.getClassicApplicants_200_response_data_inner_profile_educations_inner(
                        school = unipile.models.get_classic_applicants_200_response_data_inner_profile_educations_inner_school.getClassicApplicants_200_response_data_inner_profile_educations_inner_school(
                            id = '', 
                            name = '', 
                            picture_url = '', 
                            profile_url = '', ), 
                        degree = '', 
                        description = '', 
                        field_of_study = '', 
                        grade = '', 
                        started_on = '', 
                        ended_on = '', )
                    ],
        )
        """

    def testGetClassicApplicants200ResponseDataInnerProfile(self):
        """Test GetClassicApplicants200ResponseDataInnerProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
