# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.send_email_request_custom_headers_inner import SendEmailRequestCustomHeadersInner

class TestSendEmailRequestCustomHeadersInner(unittest.TestCase):
    """SendEmailRequestCustomHeadersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendEmailRequestCustomHeadersInner:
        """Test SendEmailRequestCustomHeadersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendEmailRequestCustomHeadersInner`
        """
        model = SendEmailRequestCustomHeadersInner()
        if include_optional:
            return SendEmailRequestCustomHeadersInner(
                name = '',
                value = ''
            )
        else:
            return SendEmailRequestCustomHeadersInner(
                name = '',
                value = '',
        )
        """

    def testSendEmailRequestCustomHeadersInner(self):
        """Test SendEmailRequestCustomHeadersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
