# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_classic_applicants_request import GetClassicApplicantsRequest

class TestGetClassicApplicantsRequest(unittest.TestCase):
    """GetClassicApplicantsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClassicApplicantsRequest:
        """Test GetClassicApplicantsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClassicApplicantsRequest`
        """
        model = GetClassicApplicantsRequest()
        if include_optional:
            return GetClassicApplicantsRequest(
                ratings = [
                    'UNRATED'
                    ],
                keywords = '',
                sort_by = 'APPLIED_DATE',
                location = [
                    ''
                    ],
                years_of_experience = [
                    unipile.models.get_classic_applicants_request_years_of_experience_inner.getClassicApplicants_request_years_of_experience_inner(
                        min = 1, 
                        max = 1, )
                    ],
                skills = [
                    ''
                    ]
            )
        else:
            return GetClassicApplicantsRequest(
        )
        """

    def testGetClassicApplicantsRequest(self):
        """Test GetClassicApplicantsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
