# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.perform_sales_companies_search_request_headcount_inner import PerformSalesCompaniesSearchRequestHeadcountInner

class TestPerformSalesCompaniesSearchRequestHeadcountInner(unittest.TestCase):
    """PerformSalesCompaniesSearchRequestHeadcountInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformSalesCompaniesSearchRequestHeadcountInner:
        """Test PerformSalesCompaniesSearchRequestHeadcountInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformSalesCompaniesSearchRequestHeadcountInner`
        """
        model = PerformSalesCompaniesSearchRequestHeadcountInner()
        if include_optional:
            return PerformSalesCompaniesSearchRequestHeadcountInner(
                min = 1,
                max = 0
            )
        else:
            return PerformSalesCompaniesSearchRequestHeadcountInner(
        )
        """

    def testPerformSalesCompaniesSearchRequestHeadcountInner(self):
        """Test PerformSalesCompaniesSearchRequestHeadcountInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
