# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.re_authenticate_existing_account import ReAuthenticateExistingAccount

class TestReAuthenticateExistingAccount(unittest.TestCase):
    """ReAuthenticateExistingAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReAuthenticateExistingAccount:
        """Test ReAuthenticateExistingAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReAuthenticateExistingAccount`
        """
        model = ReAuthenticateExistingAccount()
        if include_optional:
            return ReAuthenticateExistingAccount(
                expires_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                redirect_uri = '',
                state = '',
                config = unipile.models.link_new_account_config.Link_new_account_config(
                    google = {
                        'key' : null
                        }, 
                    outlook = {
                        'key' : null
                        }, 
                    linkedin = unipile.models.link_new_account_config_linkedin.Link_new_account_config_linkedin(
                        custom_proxy = unipile.models.custom_proxy.Custom proxy(
                            host = '', 
                            port = 1.337, 
                            username = '', 
                            password = '', 
                            protocol = 'https', ), 
                        auto_proxy_config = unipile.models.automatic_proxy_configuration.Automatic proxy configuration(
                            country = '', 
                            ip = '', ), 
                        products = [
                            'classic'
                            ], 
                        allow_methods = [
                            'credentials'
                            ], ), 
                    whatsapp = {
                        'key' : null
                        }, 
                    instagram = {
                        'key' : null
                        }, 
                    imap = { }, 
                    telegram = {
                        'key' : null
                        }, 
                    global = unipile.models.link_new_account_config_global.Link_new_account_config_global(
                        login_hint = '', 
                        allow_user_proxy_override = True, 
                        allow_user_country_override = True, 
                        wait_initial_sync = True, ), ),
                account_id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj'
            )
        else:
            return ReAuthenticateExistingAccount(
                expires_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                redirect_uri = '',
                account_id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj',
        )
        """

    def testReAuthenticateExistingAccount(self):
        """Test ReAuthenticateExistingAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
