# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.43.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.request_checkpoint200_response import RequestCheckpoint200Response

class TestRequestCheckpoint200Response(unittest.TestCase):
    """RequestCheckpoint200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCheckpoint200Response:
        """Test RequestCheckpoint200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCheckpoint200Response`
        """
        model = RequestCheckpoint200Response()
        if include_optional:
            return RequestCheckpoint200Response(
                object = 'AuthenticationQrCode',
                checkpoint = None,
                intent_id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj',
                qrcode = ''
            )
        else:
            return RequestCheckpoint200Response(
                object = 'AuthenticationQrCode',
                checkpoint = None,
                intent_id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj',
                qrcode = '',
        )
        """

    def testRequestCheckpoint200Response(self):
        """Test RequestCheckpoint200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
