# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.start_chat_request import StartChatRequest

class TestStartChatRequest(unittest.TestCase):
    """StartChatRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartChatRequest:
        """Test StartChatRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartChatRequest`
        """
        model = StartChatRequest()
        if include_optional:
            return StartChatRequest(
                text = '',
                name = '',
                users_ids = None,
                attachments = [
                    unipile.models.message_file.Message File(
                        content = '', 
                        content_type = '', 
                        filename = '', 
                        metadata = unipile.models.message_file_metadata.Message_File_metadata(
                            duration = 1.337, ), 
                        send_mode = 'native', )
                    ],
                specifics = unipile.models.start_chat_request_specifics.startChat_request_specifics(
                    linkedin = unipile.models.start_chat_request_specifics_linkedin.startChat_request_specifics_linkedin(
                        classic = unipile.models.linked_in_classic.LinkedIn Classic(
                            inmail = True, 
                            company_topic = 'SERVICE_REQUEST', 
                            relation_request_id = '', 
                            applicant = unipile.models.linked_in_classic_applicant.LinkedIn_Classic_applicant(
                                id = '', 
                                messaging_token = '', ), ), 
                        sales_navigator = unipile.models.linked_in_sales_navigator.LinkedIn Sales Navigator(
                            subject = '', ), 
                        recruiter = unipile.models.linked_in_recruiter.LinkedIn Recruiter(
                            subject = '', 
                            signature = '', 
                            visibility = 'PRIVATE', 
                            intent = 'HIRE_FOR_CLIENT', 
                            send_as = 'INMAIL', 
                            channel_type = 'CAREER_SITE', 
                            follow_up = unipile.models.linked_in_recruiter_follow_up.LinkedIn_Recruiter_follow_up(
                                subject = '', 
                                text = '', 
                                attachments = [
                                    unipile.models.message_file.Message File(
                                        content = '', 
                                        content_type = '', 
                                        filename = '', 
                                        metadata = unipile.models.message_file_metadata.Message_File_metadata(
                                            duration = 1.337, ), 
                                        send_mode = 'native', )
                                    ], 
                                scheduled_for = null, ), ), ), )
            )
        else:
            return StartChatRequest(
                text = '',
                users_ids = None,
        )
        """

    def testStartChatRequest(self):
        """Test StartChatRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
