# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_recruiter_hiring_project_list200_response_data_inner_metadata import GetRecruiterHiringProjectList200ResponseDataInnerMetadata

class TestGetRecruiterHiringProjectList200ResponseDataInnerMetadata(unittest.TestCase):
    """GetRecruiterHiringProjectList200ResponseDataInnerMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecruiterHiringProjectList200ResponseDataInnerMetadata:
        """Test GetRecruiterHiringProjectList200ResponseDataInnerMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecruiterHiringProjectList200ResponseDataInnerMetadata`
        """
        model = GetRecruiterHiringProjectList200ResponseDataInnerMetadata()
        if include_optional:
            return GetRecruiterHiringProjectList200ResponseDataInnerMetadata(
                job_title = '',
                job_posting_id = '',
                locations = [
                    unipile.models.get_recruiter_hiring_project_list_200_response_data_inner_metadata_locations_inner.getRecruiterHiringProjectList_200_response_data_inner_metadata_locations_inner(
                        name = '', 
                        timezone = '', )
                    ],
                seniority_level = '',
                employment_type = '',
                industries = [
                    ''
                    ],
                company = unipile.models.get_recruiter_hiring_project_list_200_response_data_inner_metadata_company.getRecruiterHiringProjectList_200_response_data_inner_metadata_company(
                    id = '', 
                    name = '', 
                    location = '', 
                    description = '', 
                    url = '', 
                    industries = [
                        ''
                        ], )
            )
        else:
            return GetRecruiterHiringProjectList200ResponseDataInnerMetadata(
                locations = [
                    unipile.models.get_recruiter_hiring_project_list_200_response_data_inner_metadata_locations_inner.getRecruiterHiringProjectList_200_response_data_inner_metadata_locations_inner(
                        name = '', 
                        timezone = '', )
                    ],
                industries = [
                    ''
                    ],
        )
        """

    def testGetRecruiterHiringProjectList200ResponseDataInnerMetadata(self):
        """Test GetRecruiterHiringProjectList200ResponseDataInnerMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
