# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.list_classic_user_job_postings200_response_data_inner import ListClassicUserJobPostings200ResponseDataInner

class TestListClassicUserJobPostings200ResponseDataInner(unittest.TestCase):
    """ListClassicUserJobPostings200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListClassicUserJobPostings200ResponseDataInner:
        """Test ListClassicUserJobPostings200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListClassicUserJobPostings200ResponseDataInner`
        """
        model = ListClassicUserJobPostings200ResponseDataInner()
        if include_optional:
            return ListClassicUserJobPostings200ResponseDataInner(
                object = 'JobPostingListItem',
                product = 'classic',
                id = '',
                title = '',
                company = '',
                location = '',
                state = 'DRAFT',
                applications_count = 1.337
            )
        else:
            return ListClassicUserJobPostings200ResponseDataInner(
                object = 'JobPostingListItem',
                product = 'classic',
                id = '',
                title = '',
                company = '',
                location = '',
                state = 'DRAFT',
                applications_count = 1.337,
        )
        """

    def testListClassicUserJobPostings200ResponseDataInner(self):
        """Test ListClassicUserJobPostings200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
