# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_email_contacts_list200_response_data_inner_social_handles import GetEmailContactsList200ResponseDataInnerSocialHandles

class TestGetEmailContactsList200ResponseDataInnerSocialHandles(unittest.TestCase):
    """GetEmailContactsList200ResponseDataInnerSocialHandles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEmailContactsList200ResponseDataInnerSocialHandles:
        """Test GetEmailContactsList200ResponseDataInnerSocialHandles
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEmailContactsList200ResponseDataInnerSocialHandles`
        """
        model = GetEmailContactsList200ResponseDataInnerSocialHandles()
        if include_optional:
            return GetEmailContactsList200ResponseDataInnerSocialHandles(
                linkedin = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                instagram = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                github = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                facebook = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                x = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                threads = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                tiktok = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                wechat = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                gtalk = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                qq = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                skype = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                icq = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                xmpp = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                sip = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                yahoo = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                aim = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                jabber = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                msn = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                netmeeting = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', ),
                googletalk = unipile.models.get_email_contacts_list_200_response_data_inner_social_handles_linkedin.getEmailContactsList_200_response_data_inner_social_handles_linkedin(
                    url = '', 
                    name = '', )
            )
        else:
            return GetEmailContactsList200ResponseDataInnerSocialHandles(
        )
        """

    def testGetEmailContactsList200ResponseDataInnerSocialHandles(self):
        """Test GetEmailContactsList200ResponseDataInnerSocialHandles"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
