# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.update_webhook_endpoint_request import UpdateWebhookEndpointRequest

class TestUpdateWebhookEndpointRequest(unittest.TestCase):
    """UpdateWebhookEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateWebhookEndpointRequest:
        """Test UpdateWebhookEndpointRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateWebhookEndpointRequest`
        """
        model = UpdateWebhookEndpointRequest()
        if include_optional:
            return UpdateWebhookEndpointRequest(
                trigger_events = [
                    'account.status.disconnected'
                    ],
                account_ids = [
                    'acc_jUR,rZ#UM/?R,Fp^l6$ARj'
                    ],
                url = '',
                description = '',
                enabled = True
            )
        else:
            return UpdateWebhookEndpointRequest(
        )
        """

    def testUpdateWebhookEndpointRequest(self):
        """Test UpdateWebhookEndpointRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
