# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_recruiter_job_posting_budget200_response_free import GetRecruiterJobPostingBudget200ResponseFree

class TestGetRecruiterJobPostingBudget200ResponseFree(unittest.TestCase):
    """GetRecruiterJobPostingBudget200ResponseFree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecruiterJobPostingBudget200ResponseFree:
        """Test GetRecruiterJobPostingBudget200ResponseFree
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecruiterJobPostingBudget200ResponseFree`
        """
        model = GetRecruiterJobPostingBudget200ResponseFree()
        if include_optional:
            return GetRecruiterJobPostingBudget200ResponseFree(
                eligible = True
            )
        else:
            return GetRecruiterJobPostingBudget200ResponseFree(
                eligible = True,
        )
        """

    def testGetRecruiterJobPostingBudget200ResponseFree(self):
        """Test GetRecruiterJobPostingBudget200ResponseFree"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
