# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_classic_company_profile200_response_acquired_by import GetClassicCompanyProfile200ResponseAcquiredBy

class TestGetClassicCompanyProfile200ResponseAcquiredBy(unittest.TestCase):
    """GetClassicCompanyProfile200ResponseAcquiredBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClassicCompanyProfile200ResponseAcquiredBy:
        """Test GetClassicCompanyProfile200ResponseAcquiredBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClassicCompanyProfile200ResponseAcquiredBy`
        """
        model = GetClassicCompanyProfile200ResponseAcquiredBy()
        if include_optional:
            return GetClassicCompanyProfile200ResponseAcquiredBy(
                object = 'CompanyLightProfile',
                id = '',
                name = '',
                public_identifier = '',
                profile_url = ''
            )
        else:
            return GetClassicCompanyProfile200ResponseAcquiredBy(
                object = 'CompanyLightProfile',
                id = '',
                name = '',
                public_identifier = '',
                profile_url = '',
        )
        """

    def testGetClassicCompanyProfile200ResponseAcquiredBy(self):
        """Test GetClassicCompanyProfile200ResponseAcquiredBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
