# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.people_search_data_inner import PeopleSearchDataInner

class TestPeopleSearchDataInner(unittest.TestCase):
    """PeopleSearchDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeopleSearchDataInner:
        """Test PeopleSearchDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeopleSearchDataInner`
        """
        model = PeopleSearchDataInner()
        if include_optional:
            return PeopleSearchDataInner(
                object = 'PeopleSearchResult',
                product = 'recruiter',
                visibility = 'full',
                id = '',
                candidate_id = '',
                headline = '',
                network_distance = 'SELF',
                location = '',
                is_hidden_candidate = True,
                work_experience = [
                    unipile.models.partial_profile_work_experience_inner.Partial_profile_work_experience_inner(
                        id = '', 
                        company = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_certifications_inner_organization.getUserProfile_200_response_specifics_allOf_anyOf_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        title = '', 
                        started_on = '', 
                        ended_on = '', 
                        location = '', 
                        description = '', 
                        employment_type = 'SELF_EMPLOYED', 
                        workplace_type = 'ON_SITE', 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', )
                    ],
                can_send_inmail = True,
                display_name = '',
                public_identifier = '',
                profile_url = '',
                industry = '',
                relations_count = 1.337,
                followers_count = 1.337,
                skills = [
                    unipile.models.full_profile_skills_inner.Full_profile_skills_inner(
                        name = '', 
                        endorsement_count = 1.337, )
                    ],
                summary = '',
                public_picture_url = '',
                emails = [
                    ''
                    ],
                phone_numbers = [
                    ''
                    ],
                education = [
                    unipile.models.full_profile_education_inner.Full_profile_education_inner(
                        id = '', 
                        school = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_education_inner_school.getUserProfile_200_response_specifics_allOf_anyOf_education_inner_school(
                            id = '', 
                            name = '', 
                            picture_url = '', 
                            profile_url = '', ), 
                        degree = '', 
                        description = '', 
                        activities = '', 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', 
                        grade = '', 
                        fields_of_study = [
                            ''
                            ], 
                        started_on = '', 
                        ended_on = '', )
                    ],
                languages = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_languages_inner.getUserProfile_200_response_specifics_allOf_anyOf_languages_inner(
                        language = '', 
                        proficiency = 'ELEMENTARY', )
                    ],
                certifications = [
                    unipile.models.full_profile_certifications_inner.Full_profile_certifications_inner(
                        title = '', 
                        organization = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_certifications_inner_organization.getUserProfile_200_response_specifics_allOf_anyOf_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        issued_on = '', 
                        expires_on = '', 
                        license = '', 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', 
                        url = '', )
                    ],
                projects = [
                    unipile.models.full_profile_projects_inner.Full_profile_projects_inner(
                        name = '', 
                        description = '', 
                        contributors = [
                            unipile.models.get_user_profile_200_response_specifics_all_of_any_of_projects_inner_contributors_inner.getUserProfile_200_response_specifics_allOf_anyOf_projects_inner_contributors_inner(
                                id = '', 
                                object = 'User', 
                                type = 'individual', 
                                public_identifier = '', 
                                display_name = '', 
                                profile_url = '', 
                                public_picture_url = '', 
                                private_picture_download_url = '', 
                                description = '', )
                            ], 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', 
                        started_on = '', 
                        ended_on = '', )
                    ],
                volunteering = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_volunteer_experience_inner.getUserProfile_200_response_specifics_allOf_anyOf_volunteer_experience_inner(
                        organization = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_certifications_inner_organization.getUserProfile_200_response_specifics_allOf_anyOf_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        role = '', 
                        cause = '', 
                        description = '', 
                        started_on = '', 
                        ended_on = '', )
                    ],
                recommendations = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner(
                        caption = '', 
                        created_on = '', 
                        text = '', 
                        user = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner_user.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', ), )
                    ]
            )
        else:
            return PeopleSearchDataInner(
                object = 'PeopleSearchResult',
                product = 'recruiter',
                visibility = 'full',
                id = '',
                candidate_id = '',
                headline = '',
                network_distance = 'SELF',
                location = '',
                is_hidden_candidate = True,
                work_experience = [
                    unipile.models.partial_profile_work_experience_inner.Partial_profile_work_experience_inner(
                        id = '', 
                        company = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_certifications_inner_organization.getUserProfile_200_response_specifics_allOf_anyOf_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        title = '', 
                        started_on = '', 
                        ended_on = '', 
                        location = '', 
                        description = '', 
                        employment_type = 'SELF_EMPLOYED', 
                        workplace_type = 'ON_SITE', 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', )
                    ],
                display_name = '',
                profile_url = '',
                industry = '',
                skills = [
                    unipile.models.full_profile_skills_inner.Full_profile_skills_inner(
                        name = '', 
                        endorsement_count = 1.337, )
                    ],
                education = [
                    unipile.models.full_profile_education_inner.Full_profile_education_inner(
                        id = '', 
                        school = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_education_inner_school.getUserProfile_200_response_specifics_allOf_anyOf_education_inner_school(
                            id = '', 
                            name = '', 
                            picture_url = '', 
                            profile_url = '', ), 
                        degree = '', 
                        description = '', 
                        activities = '', 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', 
                        grade = '', 
                        fields_of_study = [
                            ''
                            ], 
                        started_on = '', 
                        ended_on = '', )
                    ],
                languages = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_languages_inner.getUserProfile_200_response_specifics_allOf_anyOf_languages_inner(
                        language = '', 
                        proficiency = 'ELEMENTARY', )
                    ],
                certifications = [
                    unipile.models.full_profile_certifications_inner.Full_profile_certifications_inner(
                        title = '', 
                        organization = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_certifications_inner_organization.getUserProfile_200_response_specifics_allOf_anyOf_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        issued_on = '', 
                        expires_on = '', 
                        license = '', 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', 
                        url = '', )
                    ],
                projects = [
                    unipile.models.full_profile_projects_inner.Full_profile_projects_inner(
                        name = '', 
                        description = '', 
                        contributors = [
                            unipile.models.get_user_profile_200_response_specifics_all_of_any_of_projects_inner_contributors_inner.getUserProfile_200_response_specifics_allOf_anyOf_projects_inner_contributors_inner(
                                id = '', 
                                object = 'User', 
                                type = 'individual', 
                                public_identifier = '', 
                                display_name = '', 
                                profile_url = '', 
                                public_picture_url = '', 
                                private_picture_download_url = '', 
                                description = '', )
                            ], 
                        skills = [
                            ''
                            ], 
                        skills_preview = '', 
                        started_on = '', 
                        ended_on = '', )
                    ],
                volunteering = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_volunteer_experience_inner.getUserProfile_200_response_specifics_allOf_anyOf_volunteer_experience_inner(
                        organization = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_certifications_inner_organization.getUserProfile_200_response_specifics_allOf_anyOf_certifications_inner_organization(
                            name = '', 
                            id = '', 
                            public_identifier = '', 
                            picture_url = '', 
                            profile_url = '', 
                            industries = [
                                ''
                                ], ), 
                        role = '', 
                        cause = '', 
                        description = '', 
                        started_on = '', 
                        ended_on = '', )
                    ],
                recommendations = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner(
                        caption = '', 
                        created_on = '', 
                        text = '', 
                        user = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner_user.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', ), )
                    ],
        )
        """

    def testPeopleSearchDataInner(self):
        """Test PeopleSearchDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
