# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.update_user_profile_request_specifics_all_of_linkedin import UpdateUserProfileRequestSpecificsAllOfLinkedin

class TestUpdateUserProfileRequestSpecificsAllOfLinkedin(unittest.TestCase):
    """UpdateUserProfileRequestSpecificsAllOfLinkedin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserProfileRequestSpecificsAllOfLinkedin:
        """Test UpdateUserProfileRequestSpecificsAllOfLinkedin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserProfileRequestSpecificsAllOfLinkedin`
        """
        model = UpdateUserProfileRequestSpecificsAllOfLinkedin()
        if include_optional:
            return UpdateUserProfileRequestSpecificsAllOfLinkedin(
                skills = [
                    unipile.models.update_user_profile_request_specifics_all_of_linkedin_skills_inner.updateUserProfile_request_specifics_allOf_linkedin_skills_inner(
                        text = '', 
                        id = '4', )
                    ],
                skills_follow = True,
                postal_code = '',
                headline = '',
                experience = None,
                education = None,
                picture_options = unipile.models.update_user_profile_request_specifics_all_of_linkedin_picture_options.updateUserProfile_request_specifics_allOf_linkedin_picture_options(
                    filter = 'original', 
                    layout = unipile.models.layout.layout(), 
                    contrast = -0.3, 
                    vignette = -0.3, 
                    saturation = -0.3, 
                    brightness = -0.3, ),
                background_picture_options = unipile.models.update_user_profile_request_specifics_all_of_linkedin_picture_options.updateUserProfile_request_specifics_allOf_linkedin_picture_options(
                    filter = 'original', 
                    layout = unipile.models.layout.layout(), 
                    contrast = -0.3, 
                    vignette = -0.3, 
                    saturation = -0.3, 
                    brightness = -0.3, )
            )
        else:
            return UpdateUserProfileRequestSpecificsAllOfLinkedin(
        )
        """

    def testUpdateUserProfileRequestSpecificsAllOfLinkedin(self):
        """Test UpdateUserProfileRequestSpecificsAllOfLinkedin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
