# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.edit_classic_job_posting200_response import EditClassicJobPosting200Response

class TestEditClassicJobPosting200Response(unittest.TestCase):
    """EditClassicJobPosting200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditClassicJobPosting200Response:
        """Test EditClassicJobPosting200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditClassicJobPosting200Response`
        """
        model = EditClassicJobPosting200Response()
        if include_optional:
            return EditClassicJobPosting200Response(
                object = 'JobPostingEdited'
            )
        else:
            return EditClassicJobPosting200Response(
                object = 'JobPostingEdited',
        )
        """

    def testEditClassicJobPosting200Response(self):
        """Test EditClassicJobPosting200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
