# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.update_user_profile_request_specifics_all_of_linkedin_custom_link import UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink

class TestUpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink(unittest.TestCase):
    """UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink:
        """Test UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink`
        """
        model = UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink()
        if include_optional:
            return UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink(
                type = 'STORE',
                url = '',
                display_on = 'EVERYWHERE'
            )
        else:
            return UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink(
                type = 'STORE',
                url = '',
        )
        """

    def testUpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink(self):
        """Test UpdateUserProfileRequestSpecificsAllOfLinkedinCustomLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
