# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_messages_list200_response_data_inner import GetMessagesList200ResponseDataInner

class TestGetMessagesList200ResponseDataInner(unittest.TestCase):
    """GetMessagesList200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMessagesList200ResponseDataInner:
        """Test GetMessagesList200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMessagesList200ResponseDataInner`
        """
        model = GetMessagesList200ResponseDataInner()
        if include_optional:
            return GetMessagesList200ResponseDataInner(
                object = 'Message',
                id = '',
                text = '',
                sender_id = '',
                chat_id = '',
                timestamp = '',
                is_sender = True,
                is_hidden = True,
                is_seen = True,
                is_delivered = True,
                is_deleted = True,
                is_edited = True,
                is_pinned = True,
                is_event = True,
                is_mentionned = True,
                event_type = 0,
                event_metadata = None,
                reactions_counter = [
                    unipile.models.get_messages_list_200_response_data_inner_reactions_counter_inner.getMessagesList_200_response_data_inner_reactions_counter_inner(
                        reaction = '', 
                        count = 1.337, )
                    ],
                sender = unipile.models.get_messages_list_200_response_data_inner_sender.getMessagesList_200_response_data_inner_sender(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', ),
                provider = 'mock',
                attachments = [
                    null
                    ],
                quoted = unipile.models.get_messages_list_200_response_data_inner_quoted.getMessagesList_200_response_data_inner_quoted(
                    object = 'QuotedMessage', 
                    id = '', 
                    text = '', 
                    attachments = [
                        null
                        ], 
                    sender = unipile.models.get_messages_list_200_response_data_inner_sender.getMessagesList_200_response_data_inner_sender(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', ), ),
                forwarded = unipile.models.get_messages_list_200_response_data_inner_forwarded.getMessagesList_200_response_data_inner_forwarded(
                    text = '', 
                    attachments = [
                        null
                        ], 
                    sender = unipile.models.get_messages_list_200_response_data_inner_sender.getMessagesList_200_response_data_inner_sender(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', ), 
                    object = 'ForwardedMessage', ),
                specifics = None
            )
        else:
            return GetMessagesList200ResponseDataInner(
                object = 'Message',
                id = '',
                sender_id = '',
                chat_id = '',
                timestamp = '',
                is_sender = True,
                is_hidden = True,
                is_seen = True,
                is_delivered = True,
                is_deleted = True,
                is_edited = True,
                is_pinned = True,
                is_event = True,
                is_mentionned = True,
                reactions_counter = [
                    unipile.models.get_messages_list_200_response_data_inner_reactions_counter_inner.getMessagesList_200_response_data_inner_reactions_counter_inner(
                        reaction = '', 
                        count = 1.337, )
                    ],
                provider = 'mock',
                attachments = [
                    null
                    ],
        )
        """

    def testGetMessagesList200ResponseDataInner(self):
        """Test GetMessagesList200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
