# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.media_share import MediaShare

class TestMediaShare(unittest.TestCase):
    """MediaShare unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaShare:
        """Test MediaShare
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaShare`
        """
        model = MediaShare()
        if include_optional:
            return MediaShare(
                object = 'Attachment',
                id = '',
                file_size = 1.337,
                is_unavailable = True,
                mimetype = '',
                url = '',
                url_expires_at = '',
                content = '',
                type = 'shared_content',
                media_type = 'post',
                author = '',
                description = ''
            )
        else:
            return MediaShare(
                object = 'Attachment',
                id = '',
                mimetype = '',
                url = '',
                type = 'shared_content',
                media_type = 'post',
        )
        """

    def testMediaShare(self):
        """Test MediaShare"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
