# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.publish_in_promoted_mode_budget import PublishInPromotedModeBudget

class TestPublishInPromotedModeBudget(unittest.TestCase):
    """PublishInPromotedModeBudget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishInPromotedModeBudget:
        """Test PublishInPromotedModeBudget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishInPromotedModeBudget`
        """
        model = PublishInPromotedModeBudget()
        if include_optional:
            return PublishInPromotedModeBudget(
                currency = '012',
                amount = 1.337,
                scope = 'DAILY'
            )
        else:
            return PublishInPromotedModeBudget(
                currency = '012',
                amount = 1.337,
                scope = 'DAILY',
        )
        """

    def testPublishInPromotedModeBudget(self):
        """Test PublishInPromotedModeBudget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
