# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.39.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in1_interests_schools_inner import LinkedIn1InterestsSchoolsInner

class TestLinkedIn1InterestsSchoolsInner(unittest.TestCase):
    """LinkedIn1InterestsSchoolsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedIn1InterestsSchoolsInner:
        """Test LinkedIn1InterestsSchoolsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedIn1InterestsSchoolsInner`
        """
        model = LinkedIn1InterestsSchoolsInner()
        if include_optional:
            return LinkedIn1InterestsSchoolsInner(
                id = '',
                name = '',
                profile_url = '',
                public_picture_url = '',
                public_identifier = '',
                followers_count = 1.337,
                is_following = True,
                object = 'SchoolLightProfile'
            )
        else:
            return LinkedIn1InterestsSchoolsInner(
                id = '',
                name = '',
                object = 'SchoolLightProfile',
        )
        """

    def testLinkedIn1InterestsSchoolsInner(self):
        """Test LinkedIn1InterestsSchoolsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
