# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.create_recruiter_job_posting_draft_in_existing_project_request_rejection_settings import CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings

class TestCreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings(unittest.TestCase):
    """CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings:
        """Test CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings`
        """
        model = CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings()
        if include_optional:
            return CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings(
                send_rejection_notification = True,
                rejection_template = '',
                reject_unqualified_applicants = True,
                reject_out_of_country_applicants = True
            )
        else:
            return CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings(
        )
        """

    def testCreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings(self):
        """Test CreateRecruiterJobPostingDraftInExistingProjectRequestRejectionSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
