# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.perform_sales_people_search_request import PerformSalesPeopleSearchRequest

class TestPerformSalesPeopleSearchRequest(unittest.TestCase):
    """PerformSalesPeopleSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformSalesPeopleSearchRequest:
        """Test PerformSalesPeopleSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformSalesPeopleSearchRequest`
        """
        model = PerformSalesPeopleSearchRequest()
        if include_optional:
            return PerformSalesPeopleSearchRequest(
                keywords = '',
                save_search = unipile.models.perform_sales_people_search_request_save_search.performSalesPeopleSearch_request_save_search(
                    name = '', ),
                load_saved_search = unipile.models.perform_sales_people_search_request_load_saved_search.performSalesPeopleSearch_request_load_saved_search(
                    id = '', 
                    last_viewed_at = 1.337, ),
                load_recent_search = unipile.models.perform_sales_people_search_request_load_recent_search.performSalesPeopleSearch_request_load_recent_search(
                    id = '', ),
                current_company = unipile.models.perform_sales_people_search_request_current_company.performSalesPeopleSearch_request_current_company(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                past_company = unipile.models.perform_sales_people_search_request_past_company.performSalesPeopleSearch_request_past_company(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                company_headcount = [
                    unipile.models.perform_sales_people_search_request_company_headcount_inner.performSalesPeopleSearch_request_company_headcount_inner(
                        min = 1, 
                        max = 0, )
                    ],
                company_type = [
                    'PUBLIC_COMPANY'
                    ],
                company_location = unipile.models.perform_sales_people_search_request_company_location.performSalesPeopleSearch_request_company_location(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                function = unipile.models.perform_sales_people_search_request_function.performSalesPeopleSearch_request_function(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                current_job_title = unipile.models.perform_sales_people_search_request_current_job_title.performSalesPeopleSearch_request_current_job_title(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                past_job_title = unipile.models.perform_sales_people_search_request_past_job_title.performSalesPeopleSearch_request_past_job_title(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                seniority = unipile.models.perform_sales_people_search_request_seniority.performSalesPeopleSearch_request_seniority(
                    include = [
                        'OWNER/PARTNER'
                        ], 
                    exclude = [
                        'OWNER/PARTNER'
                        ], ),
                years_in_company = [
                    unipile.models.perform_sales_people_search_request_years_in_company_inner.performSalesPeopleSearch_request_years_in_company_inner(
                        min = 1, 
                        max = 1, )
                    ],
                years_in_position = [
                    unipile.models.perform_sales_people_search_request_years_in_position_inner.performSalesPeopleSearch_request_years_in_position_inner(
                        min = 1, 
                        max = 1, )
                    ],
                location = unipile.models.perform_sales_people_search_request_location.performSalesPeopleSearch_request_location(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                postal_code = unipile.models.perform_sales_people_search_request_postal_code.performSalesPeopleSearch_request_postal_code(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], 
                    radius = 1, ),
                industry = unipile.models.perform_sales_people_search_request_industry.performSalesPeopleSearch_request_industry(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                first_name = [
                    ''
                    ],
                last_name = [
                    ''
                    ],
                profile_language = [
                    ''
                    ],
                years_of_experience = [
                    unipile.models.perform_sales_people_search_request_years_of_experience_inner.performSalesPeopleSearch_request_years_of_experience_inner(
                        min = 1, 
                        max = 1, )
                    ],
                group = unipile.models.perform_sales_people_search_request_group.performSalesPeopleSearch_request_group(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                school = unipile.models.perform_sales_people_search_request_school.performSalesPeopleSearch_request_school(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                following_your_company = True,
                viewed_your_profile_recently = True,
                network_distance = [
                    null
                    ],
                connections_of = [
                    ''
                    ],
                past_colleague = True,
                shared_experiences = True,
                changed_jobs = True,
                posted_on_linkedin = True,
                persona = [
                    ''
                    ],
                account_list = unipile.models.perform_sales_people_search_request_account_list.performSalesPeopleSearch_request_account_list(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                lead_list = unipile.models.perform_sales_people_search_request_lead_list.performSalesPeopleSearch_request_lead_list(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                recent_interaction = unipile.models.perform_sales_people_search_request_recent_interaction.performSalesPeopleSearch_request_recent_interaction(
                    viewed_profile = True, 
                    messaged = True, ),
                saved_resources = unipile.models.perform_sales_people_search_request_saved_resources.performSalesPeopleSearch_request_saved_resources(
                    saved_leads = True, 
                    saved_accounts = True, )
            )
        else:
            return PerformSalesPeopleSearchRequest(
        )
        """

    def testPerformSalesPeopleSearchRequest(self):
        """Test PerformSalesPeopleSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
