# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.chat_name_updated import ChatNameUpdated

class TestChatNameUpdated(unittest.TestCase):
    """ChatNameUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatNameUpdated:
        """Test ChatNameUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatNameUpdated`
        """
        model = ChatNameUpdated()
        if include_optional:
            return ChatNameUpdated(
                title = ''
            )
        else:
            return ChatNameUpdated(
                title = '',
        )
        """

    def testChatNameUpdated(self):
        """Test ChatNameUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
