# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_message_reactions_list200_response_data_inner import GetMessageReactionsList200ResponseDataInner

class TestGetMessageReactionsList200ResponseDataInner(unittest.TestCase):
    """GetMessageReactionsList200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMessageReactionsList200ResponseDataInner:
        """Test GetMessageReactionsList200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMessageReactionsList200ResponseDataInner`
        """
        model = GetMessageReactionsList200ResponseDataInner()
        if include_optional:
            return GetMessageReactionsList200ResponseDataInner(
                object = 'Reaction',
                value = '',
                sender = unipile.models.get_message_reactions_list_200_response_data_inner_sender.getMessageReactionsList_200_response_data_inner_sender(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', ),
                is_sender = True
            )
        else:
            return GetMessageReactionsList200ResponseDataInner(
                object = 'Reaction',
                value = '',
                sender = unipile.models.get_message_reactions_list_200_response_data_inner_sender.getMessageReactionsList_200_response_data_inner_sender(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', ),
                is_sender = True,
        )
        """

    def testGetMessageReactionsList200ResponseDataInner(self):
        """Test GetMessageReactionsList200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
