# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_user_profile200_response_specifics_all_of_any_of_projects_inner_contributors_inner import GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner

class TestGetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner(unittest.TestCase):
    """GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner:
        """Test GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner`
        """
        model = GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner()
        if include_optional:
            return GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner(
                id = '',
                object = 'User',
                type = 'individual',
                public_identifier = '',
                display_name = '',
                profile_url = '',
                public_picture_url = '',
                private_picture_download_url = '',
                description = ''
            )
        else:
            return GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner(
                id = '',
                object = 'User',
                type = 'individual',
                display_name = '',
        )
        """

    def testGetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner(self):
        """Test GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
