# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.create_calendar_event_request import CreateCalendarEventRequest

class TestCreateCalendarEventRequest(unittest.TestCase):
    """CreateCalendarEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCalendarEventRequest:
        """Test CreateCalendarEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCalendarEventRequest`
        """
        model = CreateCalendarEventRequest()
        if include_optional:
            return CreateCalendarEventRequest(
                title = '',
                body = '',
                location = '',
                background_color = '',
                transparency = 'opaque',
                visibility = 'public',
                conference = unipile.models.get_calendar_event_list_200_response_data_inner_conference.getCalendarEventList_200_response_data_inner_conference(
                    provider = 'google_meet', 
                    url = '', ),
                is_attendees_list_hidden = True,
                attendees = [
                    unipile.models.create_calendar_event_request_attendees_inner.createCalendarEvent_request_attendees_inner(
                        email = '', )
                    ],
                recurrence = [
                    ''
                    ],
                start = None,
                end = None
            )
        else:
            return CreateCalendarEventRequest(
                title = '',
                attendees = [
                    unipile.models.create_calendar_event_request_attendees_inner.createCalendarEvent_request_attendees_inner(
                        email = '', )
                    ],
                start = None,
                end = None,
        )
        """

    def testCreateCalendarEventRequest(self):
        """Test CreateCalendarEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
