# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.daily_daily import DailyDaily

class TestDailyDaily(unittest.TestCase):
    """DailyDaily unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DailyDaily:
        """Test DailyDaily
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DailyDaily`
        """
        model = DailyDaily()
        if include_optional:
            return DailyDaily(
                currency = '012',
                amount = 1.337
            )
        else:
            return DailyDaily(
                currency = '012',
                amount = 1.337,
        )
        """

    def testDailyDaily(self):
        """Test DailyDaily"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
