# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_inboxes_list200_response_data_inner import GetInboxesList200ResponseDataInner

class TestGetInboxesList200ResponseDataInner(unittest.TestCase):
    """GetInboxesList200ResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInboxesList200ResponseDataInner:
        """Test GetInboxesList200ResponseDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInboxesList200ResponseDataInner`
        """
        model = GetInboxesList200ResponseDataInner()
        if include_optional:
            return GetInboxesList200ResponseDataInner(
                object = 'Inbox',
                id = '',
                description = '',
                disabled = True
            )
        else:
            return GetInboxesList200ResponseDataInner(
                object = 'Inbox',
                id = '',
                disabled = True,
        )
        """

    def testGetInboxesList200ResponseDataInner(self):
        """Test GetInboxesList200ResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
