# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.36.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_contacts_list200_response_data_inner_social_handles_linkedin import GetContactsList200ResponseDataInnerSocialHandlesLinkedin

class TestGetContactsList200ResponseDataInnerSocialHandlesLinkedin(unittest.TestCase):
    """GetContactsList200ResponseDataInnerSocialHandlesLinkedin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetContactsList200ResponseDataInnerSocialHandlesLinkedin:
        """Test GetContactsList200ResponseDataInnerSocialHandlesLinkedin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetContactsList200ResponseDataInnerSocialHandlesLinkedin`
        """
        model = GetContactsList200ResponseDataInnerSocialHandlesLinkedin()
        if include_optional:
            return GetContactsList200ResponseDataInnerSocialHandlesLinkedin(
                url = '',
                name = ''
            )
        else:
            return GetContactsList200ResponseDataInnerSocialHandlesLinkedin(
        )
        """

    def testGetContactsList200ResponseDataInnerSocialHandlesLinkedin(self):
        """Test GetContactsList200ResponseDataInnerSocialHandlesLinkedin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
