# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_recruiter_search_parameters_request import GetRecruiterSearchParametersRequest

class TestGetRecruiterSearchParametersRequest(unittest.TestCase):
    """GetRecruiterSearchParametersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecruiterSearchParametersRequest:
        """Test GetRecruiterSearchParametersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecruiterSearchParametersRequest`
        """
        model = GetRecruiterSearchParametersRequest()
        if include_optional:
            return GetRecruiterSearchParametersRequest(
                source = 'JOBS',
                project_id = '',
                channel_id = '',
                keywords = '',
                type = 'SKILL',
                stage_id = '',
                offset = 1.337,
                limit = 1
            )
        else:
            return GetRecruiterSearchParametersRequest(
                source = 'JOBS',
                project_id = '',
                channel_id = '',
                type = 'SKILL',
        )
        """

    def testGetRecruiterSearchParametersRequest(self):
        """Test GetRecruiterSearchParametersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
