# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.12.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.update_chat200_response import UpdateChat200Response

class TestUpdateChat200Response(unittest.TestCase):
    """UpdateChat200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateChat200Response:
        """Test UpdateChat200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateChat200Response`
        """
        model = UpdateChat200Response()
        if include_optional:
            return UpdateChat200Response(
                object = 'Chat',
                id = '',
                name = '',
                label = '',
                description = '',
                image_url = '',
                created_at = '',
                updated_at = '',
                last_message_timestamp = '',
                muted_until = None,
                creator_id = '',
                user_id = '',
                is_group = True,
                is_1to1 = True,
                is_channel = True,
                type = 'group',
                is_pinned = True,
                is_readonly = True,
                is_archived = True,
                folders = [
                    ''
                    ],
                participants_count = 1,
                unread_count = -1,
                restrictions = [
                    'send_message'
                    ],
                participants = [
                    unipile.models.update_chat_200_response_participants_inner.updateChat_200_response_participants_inner(
                        object = 'GroupParticipant', 
                        user = unipile.models.update_chat_200_response_participants_inner_user.updateChat_200_response_participants_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', 
                            specifics = null, ), 
                        is_self = True, 
                        is_admin = True, )
                    ],
                last_message = unipile.models.get_chats_list_200_response_data_inner_last_message.getChatsList_200_response_data_inner_last_message(
                    text = '', 
                    sender_display_name = '', 
                    is_sender = True, ),
                user = unipile.models.update_chat_200_response_participants_inner_user.updateChat_200_response_participants_inner_user(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', 
                    specifics = null, ),
                provider = 'mock',
                specifics = None
            )
        else:
            return UpdateChat200Response(
                object = 'Chat',
                id = '',
                name = '',
                muted_until = None,
                is_group = True,
                is_1to1 = True,
                is_channel = True,
                type = 'group',
                is_pinned = True,
                is_readonly = True,
                is_archived = True,
                folders = [
                    ''
                    ],
                unread_count = -1,
                provider = 'mock',
        )
        """

    def testUpdateChat200Response(self):
        """Test UpdateChat200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
