# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.43.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in_classic1 import LinkedInClassic1

class TestLinkedInClassic1(unittest.TestCase):
    """LinkedInClassic1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedInClassic1:
        """Test LinkedInClassic1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedInClassic1`
        """
        model = LinkedInClassic1()
        if include_optional:
            return LinkedInClassic1(
                shared_content = unipile.models.linked_in_classic_shared_content.LinkedIn_Classic_shared_content(
                    type = 'POST', 
                    id = '', )
            )
        else:
            return LinkedInClassic1(
        )
        """

    def testLinkedInClassic1(self):
        """Test LinkedInClassic1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
