# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.send_message200_response_message_id import SendMessage200ResponseMessageId

class TestSendMessage200ResponseMessageId(unittest.TestCase):
    """SendMessage200ResponseMessageId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendMessage200ResponseMessageId:
        """Test SendMessage200ResponseMessageId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendMessage200ResponseMessageId`
        """
        model = SendMessage200ResponseMessageId()
        if include_optional:
            return SendMessage200ResponseMessageId(
            )
        else:
            return SendMessage200ResponseMessageId(
        )
        """

    def testSendMessage200ResponseMessageId(self):
        """Test SendMessage200ResponseMessageId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
