# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_classic_company_profile200_response_funding_crunchbase_last_round import GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound

class TestGetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound(unittest.TestCase):
    """GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound:
        """Test GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound`
        """
        model = GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound()
        if include_optional:
            return GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound(
                announced_on = '',
                url = '',
                funding_type = '',
                investors_count = 1.337,
                lead_investors = [
                    unipile.models.get_classic_company_profile_200_response_funding_crunchbase_last_round_lead_investors_inner.getClassicCompanyProfile_200_response_funding_crunchbase_last_round_lead_investors_inner(
                        name = '', 
                        url = '', 
                        logo_url = '', )
                    ],
                money_raised = unipile.models.get_classic_company_profile_200_response_funding_crunchbase_last_round_money_raised.getClassicCompanyProfile_200_response_funding_crunchbase_last_round_money_raised(
                    amount = 1.337, 
                    currency = '', )
            )
        else:
            return GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound(
                announced_on = '',
                url = '',
                funding_type = '',
                investors_count = 1.337,
                lead_investors = [
                    unipile.models.get_classic_company_profile_200_response_funding_crunchbase_last_round_lead_investors_inner.getClassicCompanyProfile_200_response_funding_crunchbase_last_round_lead_investors_inner(
                        name = '', 
                        url = '', 
                        logo_url = '', )
                    ],
        )
        """

    def testGetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound(self):
        """Test GetClassicCompanyProfile200ResponseFundingCrunchbaseLastRound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
