# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.40.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_chats_list200_response_data_inner_last_message_any_of1_hyperlinks_inner import GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner

class TestGetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner(unittest.TestCase):
    """GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner:
        """Test GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner`
        """
        model = GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner()
        if include_optional:
            return GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner(
                url = '',
                starts_at = 1.337,
                length = 1.337
            )
        else:
            return GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner(
                url = '',
                starts_at = 1.337,
                length = 1.337,
        )
        """

    def testGetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner(self):
        """Test GetChatsList200ResponseDataInnerLastMessageAnyOf1HyperlinksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
