# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.37.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in1_interests_groups_inner import LinkedIn1InterestsGroupsInner

class TestLinkedIn1InterestsGroupsInner(unittest.TestCase):
    """LinkedIn1InterestsGroupsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedIn1InterestsGroupsInner:
        """Test LinkedIn1InterestsGroupsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedIn1InterestsGroupsInner`
        """
        model = LinkedIn1InterestsGroupsInner()
        if include_optional:
            return LinkedIn1InterestsGroupsInner(
                id = '',
                name = '',
                url = '',
                members_count = 1.337,
                is_member = True,
                public_picture_url = ''
            )
        else:
            return LinkedIn1InterestsGroupsInner(
                name = '',
                is_member = True,
        )
        """

    def testLinkedIn1InterestsGroupsInner(self):
        """Test LinkedIn1InterestsGroupsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
