# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_user_profile200_response_specifics_all_of_any_of_recommendations import GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations

class TestGetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations(unittest.TestCase):
    """GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations:
        """Test GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations`
        """
        model = GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations()
        if include_optional:
            return GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations(
                received = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner(
                        caption = '', 
                        created_on = '', 
                        text = '', 
                        user = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner_user.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', ), )
                    ],
                given = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner(
                        caption = '', 
                        created_on = '', 
                        text = '', 
                        user = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner_user.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', ), )
                    ]
            )
        else:
            return GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations(
                received = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner(
                        caption = '', 
                        created_on = '', 
                        text = '', 
                        user = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner_user.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', ), )
                    ],
                given = [
                    unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner(
                        caption = '', 
                        created_on = '', 
                        text = '', 
                        user = unipile.models.get_user_profile_200_response_specifics_all_of_any_of_recommendations_received_inner_user.getUserProfile_200_response_specifics_allOf_anyOf_recommendations_received_inner_user(
                            id = '', 
                            object = 'User', 
                            type = 'individual', 
                            public_identifier = '', 
                            display_name = '', 
                            profile_url = '', 
                            public_picture_url = '', 
                            private_picture_download_url = '', 
                            description = '', ), )
                    ],
        )
        """

    def testGetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations(self):
        """Test GetUserProfile200ResponseSpecificsAllOfAnyOfRecommendations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
