# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.full_profile_skills_inner import FullProfileSkillsInner

class TestFullProfileSkillsInner(unittest.TestCase):
    """FullProfileSkillsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FullProfileSkillsInner:
        """Test FullProfileSkillsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FullProfileSkillsInner`
        """
        model = FullProfileSkillsInner()
        if include_optional:
            return FullProfileSkillsInner(
                name = '',
                endorsement_count = 1.337
            )
        else:
            return FullProfileSkillsInner(
                name = '',
                endorsement_count = 1.337,
        )
        """

    def testFullProfileSkillsInner(self):
        """Test FullProfileSkillsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
