# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.checkpoint_checkpoint import CheckpointCheckpoint

class TestCheckpointCheckpoint(unittest.TestCase):
    """CheckpointCheckpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckpointCheckpoint:
        """Test CheckpointCheckpoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckpointCheckpoint`
        """
        model = CheckpointCheckpoint()
        if include_optional:
            return CheckpointCheckpoint(
                type = 'OTP',
                platform = 'SMS',
                public_key = '',
                data = ''
            )
        else:
            return CheckpointCheckpoint(
                type = 'OTP',
                platform = 'SMS',
                public_key = '',
                data = '',
        )
        """

    def testCheckpointCheckpoint(self):
        """Test CheckpointCheckpoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
