# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.start_chat_request_specifics import StartChatRequestSpecifics

class TestStartChatRequestSpecifics(unittest.TestCase):
    """StartChatRequestSpecifics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartChatRequestSpecifics:
        """Test StartChatRequestSpecifics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartChatRequestSpecifics`
        """
        model = StartChatRequestSpecifics()
        if include_optional:
            return StartChatRequestSpecifics(
                linkedin = unipile.models.start_chat_request_specifics_linkedin.startChat_request_specifics_linkedin(
                    classic = unipile.models.linked_in_classic.LinkedIn Classic(
                        inmail = True, 
                        company_topic = 'SERVICE_REQUEST', 
                        relation_request_id = '', 
                        applicant = unipile.models.linked_in_classic_applicant.LinkedIn_Classic_applicant(
                            id = '', 
                            messaging_token = '', ), ), 
                    sales_navigator = unipile.models.linked_in_sales_navigator.LinkedIn Sales Navigator(
                        subject = '', ), 
                    recruiter = unipile.models.linked_in_recruiter.LinkedIn Recruiter(
                        subject = '', 
                        signature = '', 
                        visibility = 'PRIVATE', 
                        intent = 'HIRE_FOR_CLIENT', 
                        send_as = 'INMAIL', 
                        channel_type = 'CAREER_SITE', 
                        follow_up = unipile.models.linked_in_recruiter_follow_up.LinkedIn_Recruiter_follow_up(
                            subject = '', 
                            text = '', 
                            attachments = [
                                unipile.models.message_file.Message File()
                                ], 
                            scheduled_for = null, ), ), )
            )
        else:
            return StartChatRequestSpecifics(
        )
        """

    def testStartChatRequestSpecifics(self):
        """Test StartChatRequestSpecifics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
