# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_emails_list200_response import GetEmailsList200Response

class TestGetEmailsList200Response(unittest.TestCase):
    """GetEmailsList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEmailsList200Response:
        """Test GetEmailsList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEmailsList200Response`
        """
        model = GetEmailsList200Response()
        if include_optional:
            return GetEmailsList200Response(
                data = [
                    unipile.models.get_emails_list_200_response_data_inner.getEmailsList_200_response_data_inner(
                        object = 'Email', 
                        id = '', 
                        message_id = '', 
                        thread_id = '', 
                        body = '', 
                        snippet = '', 
                        subject = '', 
                        headers = [
                            unipile.models.get_emails_list_200_response_data_inner_headers_inner.getEmailsList_200_response_data_inner_headers_inner(
                                name = '', 
                                value = '', )
                            ], 
                        from = [
                            unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                                email = '', 
                                display_name = '', )
                            ], 
                        to = [
                            unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                                email = '', 
                                display_name = '', )
                            ], 
                        cc = [
                            
                            ], 
                        bcc = [
                            
                            ], 
                        reply_to = [
                            
                            ], 
                        date = '', 
                        attachments = [
                            null
                            ], 
                        folders = [
                            ''
                            ], 
                        categories = [
                            ''
                            ], 
                        is_unread = True, )
                    ],
                total_count = 1.337,
                next_cursor = ''
            )
        else:
            return GetEmailsList200Response(
                data = [
                    unipile.models.get_emails_list_200_response_data_inner.getEmailsList_200_response_data_inner(
                        object = 'Email', 
                        id = '', 
                        message_id = '', 
                        thread_id = '', 
                        body = '', 
                        snippet = '', 
                        subject = '', 
                        headers = [
                            unipile.models.get_emails_list_200_response_data_inner_headers_inner.getEmailsList_200_response_data_inner_headers_inner(
                                name = '', 
                                value = '', )
                            ], 
                        from = [
                            unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                                email = '', 
                                display_name = '', )
                            ], 
                        to = [
                            unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                                email = '', 
                                display_name = '', )
                            ], 
                        cc = [
                            
                            ], 
                        bcc = [
                            
                            ], 
                        reply_to = [
                            
                            ], 
                        date = '', 
                        attachments = [
                            null
                            ], 
                        folders = [
                            ''
                            ], 
                        categories = [
                            ''
                            ], 
                        is_unread = True, )
                    ],
        )
        """

    def testGetEmailsList200Response(self):
        """Test GetEmailsList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
