# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in_relation_request import LinkedInRelationRequest

class TestLinkedInRelationRequest(unittest.TestCase):
    """LinkedInRelationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedInRelationRequest:
        """Test LinkedInRelationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedInRelationRequest`
        """
        model = LinkedInRelationRequest()
        if include_optional:
            return LinkedInRelationRequest(
                object = 'RelationRequest',
                user = unipile.models.linked_in_relation_request_user.LinkedIn_relation_request_user(
                    id = '', 
                    object = 'User', 
                    type = 'individual', 
                    public_identifier = '', 
                    display_name = '', 
                    profile_url = '', 
                    public_picture_url = '', 
                    private_picture_download_url = '', 
                    description = '', ),
                type = 'sent',
                id = '',
                created_at = '',
                message = ''
            )
        else:
            return LinkedInRelationRequest(
                object = 'RelationRequest',
                type = 'sent',
                id = '',
        )
        """

    def testLinkedInRelationRequest(self):
        """Test LinkedInRelationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
