# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.perform_recruiter_people_search_from_talent_pool_request_spoken_language_inner import PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner

class TestPerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner(unittest.TestCase):
    """PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner:
        """Test PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner`
        """
        model = PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner()
        if include_optional:
            return PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner(
                id = '',
                priority = 'CAN_HAVE',
                proficiency = 'ELEMENTARY'
            )
        else:
            return PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner(
                id = '',
        )
        """

    def testPerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner(self):
        """Test PerformRecruiterPeopleSearchFromTalentPoolRequestSpokenLanguageInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
