# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.21.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in_interests_top_voices_inner_specifics import LinkedInInterestsTopVoicesInnerSpecifics

class TestLinkedInInterestsTopVoicesInnerSpecifics(unittest.TestCase):
    """LinkedInInterestsTopVoicesInnerSpecifics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedInInterestsTopVoicesInnerSpecifics:
        """Test LinkedInInterestsTopVoicesInnerSpecifics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedInInterestsTopVoicesInnerSpecifics`
        """
        model = LinkedInInterestsTopVoicesInnerSpecifics()
        if include_optional:
            return LinkedInInterestsTopVoicesInnerSpecifics(
                location = '',
                network_distance = 'SELF',
                industry = '',
                is_following = True,
                followers_count = 1.337,
                relations_count = 1.337,
                shared_relations_count = 1.337,
                website_url = '',
                portfolio_url = '',
                services_page_url = '',
                is_premium = True,
                is_verified = True
            )
        else:
            return LinkedInInterestsTopVoicesInnerSpecifics(
        )
        """

    def testLinkedInInterestsTopVoicesInnerSpecifics(self):
        """Test LinkedInInterestsTopVoicesInnerSpecifics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
