# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.remove_message_reaction200_response import RemoveMessageReaction200Response

class TestRemoveMessageReaction200Response(unittest.TestCase):
    """RemoveMessageReaction200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoveMessageReaction200Response:
        """Test RemoveMessageReaction200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoveMessageReaction200Response`
        """
        model = RemoveMessageReaction200Response()
        if include_optional:
            return RemoveMessageReaction200Response(
                object = 'MessageReactionRemoved'
            )
        else:
            return RemoveMessageReaction200Response(
                object = 'MessageReactionRemoved',
        )
        """

    def testRemoveMessageReaction200Response(self):
        """Test RemoveMessageReaction200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
