# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.apply_on_linkedin1 import ApplyOnLinkedin1

class TestApplyOnLinkedin1(unittest.TestCase):
    """ApplyOnLinkedin1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyOnLinkedin1:
        """Test ApplyOnLinkedin1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyOnLinkedin1`
        """
        model = ApplyOnLinkedin1()
        if include_optional:
            return ApplyOnLinkedin1(
                method = 'linkedin',
                notification_email = '',
                resume_required = True
            )
        else:
            return ApplyOnLinkedin1(
                method = 'linkedin',
                notification_email = '',
                resume_required = True,
        )
        """

    def testApplyOnLinkedin1(self):
        """Test ApplyOnLinkedin1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
