# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.46.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.content_relation import ContentRelation

class TestContentRelation(unittest.TestCase):
    """ContentRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentRelation:
        """Test ContentRelation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentRelation`
        """
        model = ContentRelation()
        if include_optional:
            return ContentRelation(
                type = 'reply_to',
                attachment_id = ''
            )
        else:
            return ContentRelation(
                type = 'reply_to',
        )
        """

    def testContentRelation(self):
        """Test ContentRelation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
