# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.create_calendar_event_request_attendees_inner import CreateCalendarEventRequestAttendeesInner

class TestCreateCalendarEventRequestAttendeesInner(unittest.TestCase):
    """CreateCalendarEventRequestAttendeesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCalendarEventRequestAttendeesInner:
        """Test CreateCalendarEventRequestAttendeesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCalendarEventRequestAttendeesInner`
        """
        model = CreateCalendarEventRequestAttendeesInner()
        if include_optional:
            return CreateCalendarEventRequestAttendeesInner(
                email = ''
            )
        else:
            return CreateCalendarEventRequestAttendeesInner(
                email = '',
        )
        """

    def testCreateCalendarEventRequestAttendeesInner(self):
        """Test CreateCalendarEventRequestAttendeesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
