# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.13.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_posts_list200_response_data_inner_quoted_post_specifics_job_posting_company import GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany

class TestGetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany(unittest.TestCase):
    """GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany:
        """Test GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany`
        """
        model = GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany()
        if include_optional:
            return GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany(
                id = '',
                name = '',
                picture_url = ''
            )
        else:
            return GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany(
                id = '',
                name = '',
        )
        """

    def testGetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany(self):
        """Test GetPostsList200ResponseDataInnerQuotedPostSpecificsJobPostingCompany"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
