# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.people_search1_data_inner_latest_contact import PeopleSearch1DataInnerLatestContact

class TestPeopleSearch1DataInnerLatestContact(unittest.TestCase):
    """PeopleSearch1DataInnerLatestContact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeopleSearch1DataInnerLatestContact:
        """Test PeopleSearch1DataInnerLatestContact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeopleSearch1DataInnerLatestContact`
        """
        model = PeopleSearch1DataInnerLatestContact()
        if include_optional:
            return PeopleSearch1DataInnerLatestContact(
                type = 'MESSAGE',
                performed_at = '',
                resource_id = ''
            )
        else:
            return PeopleSearch1DataInnerLatestContact(
                type = 'MESSAGE',
                performed_at = '',
        )
        """

    def testPeopleSearch1DataInnerLatestContact(self):
        """Test PeopleSearch1DataInnerLatestContact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
