# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_recruiter_job_posting_by_project_id200_response import GetRecruiterJobPostingByProjectId200Response

class TestGetRecruiterJobPostingByProjectId200Response(unittest.TestCase):
    """GetRecruiterJobPostingByProjectId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecruiterJobPostingByProjectId200Response:
        """Test GetRecruiterJobPostingByProjectId200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecruiterJobPostingByProjectId200Response`
        """
        model = GetRecruiterJobPostingByProjectId200Response()
        if include_optional:
            return GetRecruiterJobPostingByProjectId200Response(
                object = 'JobPosting',
                product = 'recruiter',
                id = '',
                project_id = '',
                title = '',
                company = unipile.models.get_recruiter_job_posting_by_project_id_200_response_company.getRecruiterJobPostingByProjectId_200_response_company(
                    id = '', 
                    name = '', 
                    public_picture_url = '', 
                    profile_url = '', ),
                location = '',
                state = 'DRAFT',
                workplace_type = 'ON_SITE',
                industries = [
                    ''
                    ],
                job_functions = [
                    ''
                    ],
                employment_status = 'FULL_TIME',
                experience_level = 'INTERNSHIP',
                published_at = '',
                expires_at = '',
                closed_at = '',
                description = '',
                views_count = 1.337,
                applications_count = 1.337,
                company_apply_url = '',
                tracking_pixel_url = '',
                screening_questions = [
                    unipile.models.get_recruiter_job_posting_by_project_id_200_response_screening_questions_inner.getRecruiterJobPostingByProjectId_200_response_screening_questions_inner(
                        question = '', 
                        is_eliminatory = True, 
                        choices = [
                            null
                            ], )
                    ],
                hiring_team = [
                    unipile.models.get_recruiter_job_posting_by_project_id_200_response_hiring_team_inner.getRecruiterJobPostingByProjectId_200_response_hiring_team_inner(
                        id = '', 
                        full_name = '', 
                        public_picture_url = '', )
                    ]
            )
        else:
            return GetRecruiterJobPostingByProjectId200Response(
                object = 'JobPosting',
                product = 'recruiter',
                id = '',
                project_id = '',
                title = '',
                company = unipile.models.get_recruiter_job_posting_by_project_id_200_response_company.getRecruiterJobPostingByProjectId_200_response_company(
                    id = '', 
                    name = '', 
                    public_picture_url = '', 
                    profile_url = '', ),
                location = '',
                state = 'DRAFT',
                workplace_type = 'ON_SITE',
                industries = [
                    ''
                    ],
                job_functions = [
                    ''
                    ],
                employment_status = 'FULL_TIME',
                experience_level = 'INTERNSHIP',
                description = '',
                views_count = 1.337,
                applications_count = 1.337,
                hiring_team = [
                    unipile.models.get_recruiter_job_posting_by_project_id_200_response_hiring_team_inner.getRecruiterJobPostingByProjectId_200_response_hiring_team_inner(
                        id = '', 
                        full_name = '', 
                        public_picture_url = '', )
                    ],
        )
        """

    def testGetRecruiterJobPostingByProjectId200Response(self):
        """Test GetRecruiterJobPostingByProjectId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
