# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.checkpoint import Checkpoint

class TestCheckpoint(unittest.TestCase):
    """Checkpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Checkpoint:
        """Test Checkpoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Checkpoint`
        """
        model = Checkpoint()
        if include_optional:
            return Checkpoint(
                object = 'AuthenticationCheckpoint',
                checkpoint = None,
                intent_id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj'
            )
        else:
            return Checkpoint(
                object = 'AuthenticationCheckpoint',
                checkpoint = None,
                intent_id = 'acc_jUR,rZ#UM/?R,Fp^l6$ARj',
        )
        """

    def testCheckpoint(self):
        """Test Checkpoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
