# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.link_new_account_config_imap import LinkNewAccountConfigImap

class TestLinkNewAccountConfigImap(unittest.TestCase):
    """LinkNewAccountConfigImap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkNewAccountConfigImap:
        """Test LinkNewAccountConfigImap
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkNewAccountConfigImap`
        """
        model = LinkNewAccountConfigImap()
        if include_optional:
            return LinkNewAccountConfigImap(
                custom_proxy = unipile.models.custom_proxy.Custom proxy(
                    host = '', 
                    port = 1.337, 
                    username = '', 
                    password = '', 
                    protocol = 'https', ),
                initial_sync_enable = True
            )
        else:
            return LinkNewAccountConfigImap(
                initial_sync_enable = True,
        )
        """

    def testLinkNewAccountConfigImap(self):
        """Test LinkNewAccountConfigImap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
