# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.publish_in_promoted_mode1_budget_any_of1 import PublishInPromotedMode1BudgetAnyOf1

class TestPublishInPromotedMode1BudgetAnyOf1(unittest.TestCase):
    """PublishInPromotedMode1BudgetAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishInPromotedMode1BudgetAnyOf1:
        """Test PublishInPromotedMode1BudgetAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishInPromotedMode1BudgetAnyOf1`
        """
        model = PublishInPromotedMode1BudgetAnyOf1()
        if include_optional:
            return PublishInPromotedMode1BudgetAnyOf1(
                total = unipile.models.daily_daily.Daily_daily(
                    currency = '012', 
                    amount = 1.337, )
            )
        else:
            return PublishInPromotedMode1BudgetAnyOf1(
                total = unipile.models.daily_daily.Daily_daily(
                    currency = '012', 
                    amount = 1.337, ),
        )
        """

    def testPublishInPromotedMode1BudgetAnyOf1(self):
        """Test PublishInPromotedMode1BudgetAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
