# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.get_thread200_response_emails_inner import GetThread200ResponseEmailsInner

class TestGetThread200ResponseEmailsInner(unittest.TestCase):
    """GetThread200ResponseEmailsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetThread200ResponseEmailsInner:
        """Test GetThread200ResponseEmailsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetThread200ResponseEmailsInner`
        """
        model = GetThread200ResponseEmailsInner()
        if include_optional:
            return GetThread200ResponseEmailsInner(
                object = 'Email',
                id = '',
                message_id = '',
                thread_id = '',
                body = '',
                snippet = '',
                subject = '',
                headers = [
                    unipile.models.get_emails_list_200_response_data_inner_headers_inner.getEmailsList_200_response_data_inner_headers_inner(
                        name = '', 
                        value = '', )
                    ],
                var_from = [
                    unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                        email = '', 
                        display_name = '', )
                    ],
                to = [
                    unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                        email = '', 
                        display_name = '', )
                    ],
                cc = [
                    unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                        email = '', 
                        display_name = '', )
                    ],
                bcc = [
                    unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                        email = '', 
                        display_name = '', )
                    ],
                reply_to = [
                    unipile.models.get_emails_list_200_response_data_inner_from_inner.getEmailsList_200_response_data_inner_from_inner(
                        email = '', 
                        display_name = '', )
                    ],
                var_date = '',
                attachments = [
                    null
                    ],
                folders = [
                    ''
                    ],
                categories = [
                    ''
                    ],
                is_unread = True
            )
        else:
            return GetThread200ResponseEmailsInner(
                object = 'Email',
                id = '',
                message_id = '',
                body = '',
                snippet = '',
                subject = '',
                headers = [
                    unipile.models.get_emails_list_200_response_data_inner_headers_inner.getEmailsList_200_response_data_inner_headers_inner(
                        name = '', 
                        value = '', )
                    ],
                var_date = '',
                attachments = [
                    null
                    ],
                folders = [
                    ''
                    ],
                is_unread = True,
        )
        """

    def testGetThread200ResponseEmailsInner(self):
        """Test GetThread200ResponseEmailsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
