# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.remove_post_reaction200_response import RemovePostReaction200Response

class TestRemovePostReaction200Response(unittest.TestCase):
    """RemovePostReaction200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemovePostReaction200Response:
        """Test RemovePostReaction200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemovePostReaction200Response`
        """
        model = RemovePostReaction200Response()
        if include_optional:
            return RemovePostReaction200Response(
                object = 'PostReactionRemoved'
            )
        else:
            return RemovePostReaction200Response(
                object = 'PostReactionRemoved',
        )
        """

    def testRemovePostReaction200Response(self):
        """Test RemovePostReaction200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
