# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.create_classic_job_posting_draft_request_company import CreateClassicJobPostingDraftRequestCompany

class TestCreateClassicJobPostingDraftRequestCompany(unittest.TestCase):
    """CreateClassicJobPostingDraftRequestCompany unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateClassicJobPostingDraftRequestCompany:
        """Test CreateClassicJobPostingDraftRequestCompany
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateClassicJobPostingDraftRequestCompany`
        """
        model = CreateClassicJobPostingDraftRequestCompany()
        if include_optional:
            return CreateClassicJobPostingDraftRequestCompany(
                id = '',
                name = ''
            )
        else:
            return CreateClassicJobPostingDraftRequestCompany(
        )
        """

    def testCreateClassicJobPostingDraftRequestCompany(self):
        """Test CreateClassicJobPostingDraftRequestCompany"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
