# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.recruiter_saved_search import RecruiterSavedSearch

class TestRecruiterSavedSearch(unittest.TestCase):
    """RecruiterSavedSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecruiterSavedSearch:
        """Test RecruiterSavedSearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecruiterSavedSearch`
        """
        model = RecruiterSavedSearch()
        if include_optional:
            return RecruiterSavedSearch(
                object = 'SavedSearchMetadata',
                product = 'recruiter',
                query = '',
                new_results_count = 1.337,
                project = unipile.models.recruiter_saved_search_project.Recruiter_saved_search_project(
                    id = '', 
                    name = '', )
            )
        else:
            return RecruiterSavedSearch(
                object = 'SavedSearchMetadata',
                product = 'recruiter',
                query = '',
                new_results_count = 1.337,
        )
        """

    def testRecruiterSavedSearch(self):
        """Test RecruiterSavedSearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
