# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.chat_subject_updated import ChatSubjectUpdated

class TestChatSubjectUpdated(unittest.TestCase):
    """ChatSubjectUpdated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatSubjectUpdated:
        """Test ChatSubjectUpdated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatSubjectUpdated`
        """
        model = ChatSubjectUpdated()
        if include_optional:
            return ChatSubjectUpdated(
                subject = ''
            )
        else:
            return ChatSubjectUpdated(
        )
        """

    def testChatSubjectUpdated(self):
        """Test ChatSubjectUpdated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
