# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.35.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unipile.models.linked_in1_projects_inner import LinkedIn1ProjectsInner

class TestLinkedIn1ProjectsInner(unittest.TestCase):
    """LinkedIn1ProjectsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkedIn1ProjectsInner:
        """Test LinkedIn1ProjectsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkedIn1ProjectsInner`
        """
        model = LinkedIn1ProjectsInner()
        if include_optional:
            return LinkedIn1ProjectsInner(
                name = '',
                description = '',
                contributors = [
                    unipile.models.linked_in_1_projects_inner_contributors_inner.LinkedIn_1_projects_inner_contributors_inner(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', 
                        specifics = null, )
                    ],
                skills = [
                    ''
                    ],
                skills_preview = '',
                started_on = '',
                ended_on = ''
            )
        else:
            return LinkedIn1ProjectsInner(
                name = '',
                contributors = [
                    unipile.models.linked_in_1_projects_inner_contributors_inner.LinkedIn_1_projects_inner_contributors_inner(
                        id = '', 
                        object = 'User', 
                        type = 'individual', 
                        public_identifier = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        profile_url = '', 
                        public_picture_url = '', 
                        private_picture_download_url = '', 
                        description = '', 
                        specifics = null, )
                    ],
        )
        """

    def testLinkedIn1ProjectsInner(self):
        """Test LinkedIn1ProjectsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
