# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from unipile.models.full_profile_education_inner import FullProfileEducationInner
from unipile.models.full_profile_skills_inner import FullProfileSkillsInner
from unipile.models.lead_list_data_inner_all_of_all_of_contact_info import LeadListDataInnerAllOfAllOfContactInfo
from unipile.models.lead_list_data_inner_all_of_all_of_social_handles import LeadListDataInnerAllOfAllOfSocialHandles
from unipile.models.linked_in_languages_inner import LinkedInLanguagesInner
from unipile.models.linked_in_volunteer_experience_inner import LinkedInVolunteerExperienceInner
from unipile.models.partial_profile_work_experience_inner import PartialProfileWorkExperienceInner
from unipile.models.people_search1_data_inner_latest_contact import PeopleSearch1DataInnerLatestContact
from unipile.models.people_search1_data_inner_network_distance import PeopleSearch1DataInnerNetworkDistance
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountListDataInnerRecommendedLead(BaseModel):
    """
    A recommended lead associated with the Account.
    """ # noqa: E501
    id: StrictStr = Field(description="The ID of the user.")
    member_id: Optional[StrictStr] = Field(default=None, description="The LinkedIn internal member ID of the user.")
    display_name: StrictStr = Field(description="The display name of the User.")
    public_identifier: Optional[StrictStr] = Field(default=None, description="The public identifier of the User.")
    profile_url: Optional[StrictStr] = Field(default=None, description="The profile URL of the User.")
    public_picture_url: Optional[StrictStr] = Field(default=None, description="The public picture URL of the User.")
    public_picture_url_large: Optional[StrictStr] = Field(default=None, description="The public picture URL of the User in large size.")
    relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of relations of the User.")
    location: Optional[StrictStr] = Field(default=None, description="The location of the User.")
    headline: Optional[StrictStr] = Field(default=None, description="The headline of the User.")
    network_distance: PeopleSearch1DataInnerNetworkDistance
    can_send_inmail: Optional[StrictBool] = Field(default=None, description="Whether it is possible to send an inMail to this User.")
    shared_relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of relations that you share with the User.")
    summary: Optional[StrictStr] = Field(default=None, description="The summary of the User.")
    has_posted_recently: StrictBool = Field(description="Whether the User has posted recently.")
    has_viewed_your_profile: StrictBool = Field(description="Whether the User has already visited your profile.")
    was_hired_recently: StrictBool = Field(description="Whether the User was hired recently.")
    was_promoted_recently: StrictBool = Field(description="Whether the User was promoted recently.")
    follows_your_company: StrictBool = Field(description="Whether the User is folliwing your company.")
    is_premium: StrictBool = Field(description="Whether the User has a premium subscription.")
    is_past_colleague: StrictBool = Field(description="Whether the User is a past colleague of yours.")
    is_open_profile: StrictBool = Field(description="Whether the User has an Open Profile. The Open Profile feature allows anyone on LinkedIn to contact a Premium member for free.")
    websites: Optional[List[StrictStr]] = Field(default=None, description="A list of websites of the User.")
    addresses: Optional[List[StrictStr]] = Field(default=None, description="A list of addresses of the User.")
    contact_info: LeadListDataInnerAllOfAllOfContactInfo
    latest_contact: Optional[PeopleSearch1DataInnerLatestContact] = None
    lists_count: Union[StrictFloat, StrictInt] = Field(description="The number of lists you own on which the User appears.")
    notes_count: Union[StrictFloat, StrictInt] = Field(description="The number of notes you own about the User.")
    social_handles: Optional[LeadListDataInnerAllOfAllOfSocialHandles] = None
    education: List[FullProfileEducationInner]
    skills: List[FullProfileSkillsInner]
    work_experience: List[PartialProfileWorkExperienceInner]
    languages: List[LinkedInLanguagesInner]
    volunteering: List[LinkedInVolunteerExperienceInner]
    object: StrictStr
    __properties: ClassVar[List[str]] = ["id", "member_id", "display_name", "public_identifier", "profile_url", "public_picture_url", "public_picture_url_large", "relations_count", "location", "headline", "network_distance", "can_send_inmail", "shared_relations_count", "summary", "has_posted_recently", "has_viewed_your_profile", "was_hired_recently", "was_promoted_recently", "follows_your_company", "is_premium", "is_past_colleague", "is_open_profile", "websites", "addresses", "contact_info", "latest_contact", "lists_count", "notes_count", "social_handles", "education", "skills", "work_experience", "languages", "volunteering", "object"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Lead']):
            raise ValueError("must be one of enum values ('Lead')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountListDataInnerRecommendedLead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of network_distance
        if self.network_distance:
            _dict['network_distance'] = self.network_distance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_info
        if self.contact_info:
            _dict['contact_info'] = self.contact_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of latest_contact
        if self.latest_contact:
            _dict['latest_contact'] = self.latest_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of social_handles
        if self.social_handles:
            _dict['social_handles'] = self.social_handles.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in education (list)
        _items = []
        if self.education:
            for _item_education in self.education:
                if _item_education:
                    _items.append(_item_education.to_dict())
            _dict['education'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in skills (list)
        _items = []
        if self.skills:
            for _item_skills in self.skills:
                if _item_skills:
                    _items.append(_item_skills.to_dict())
            _dict['skills'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in work_experience (list)
        _items = []
        if self.work_experience:
            for _item_work_experience in self.work_experience:
                if _item_work_experience:
                    _items.append(_item_work_experience.to_dict())
            _dict['work_experience'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in languages (list)
        _items = []
        if self.languages:
            for _item_languages in self.languages:
                if _item_languages:
                    _items.append(_item_languages.to_dict())
            _dict['languages'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volunteering (list)
        _items = []
        if self.volunteering:
            for _item_volunteering in self.volunteering:
                if _item_volunteering:
                    _items.append(_item_volunteering.to_dict())
            _dict['volunteering'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountListDataInnerRecommendedLead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "member_id": obj.get("member_id"),
            "display_name": obj.get("display_name"),
            "public_identifier": obj.get("public_identifier"),
            "profile_url": obj.get("profile_url"),
            "public_picture_url": obj.get("public_picture_url"),
            "public_picture_url_large": obj.get("public_picture_url_large"),
            "relations_count": obj.get("relations_count"),
            "location": obj.get("location"),
            "headline": obj.get("headline"),
            "network_distance": PeopleSearch1DataInnerNetworkDistance.from_dict(obj["network_distance"]) if obj.get("network_distance") is not None else None,
            "can_send_inmail": obj.get("can_send_inmail"),
            "shared_relations_count": obj.get("shared_relations_count"),
            "summary": obj.get("summary"),
            "has_posted_recently": obj.get("has_posted_recently"),
            "has_viewed_your_profile": obj.get("has_viewed_your_profile"),
            "was_hired_recently": obj.get("was_hired_recently"),
            "was_promoted_recently": obj.get("was_promoted_recently"),
            "follows_your_company": obj.get("follows_your_company"),
            "is_premium": obj.get("is_premium"),
            "is_past_colleague": obj.get("is_past_colleague"),
            "is_open_profile": obj.get("is_open_profile"),
            "websites": obj.get("websites"),
            "addresses": obj.get("addresses"),
            "contact_info": LeadListDataInnerAllOfAllOfContactInfo.from_dict(obj["contact_info"]) if obj.get("contact_info") is not None else None,
            "latest_contact": PeopleSearch1DataInnerLatestContact.from_dict(obj["latest_contact"]) if obj.get("latest_contact") is not None else None,
            "lists_count": obj.get("lists_count"),
            "notes_count": obj.get("notes_count"),
            "social_handles": LeadListDataInnerAllOfAllOfSocialHandles.from_dict(obj["social_handles"]) if obj.get("social_handles") is not None else None,
            "education": [FullProfileEducationInner.from_dict(_item) for _item in obj["education"]] if obj.get("education") is not None else None,
            "skills": [FullProfileSkillsInner.from_dict(_item) for _item in obj["skills"]] if obj.get("skills") is not None else None,
            "work_experience": [PartialProfileWorkExperienceInner.from_dict(_item) for _item in obj["work_experience"]] if obj.get("work_experience") is not None else None,
            "languages": [LinkedInLanguagesInner.from_dict(_item) for _item in obj["languages"]] if obj.get("languages") is not None else None,
            "volunteering": [LinkedInVolunteerExperienceInner.from_dict(_item) for _item in obj["volunteering"]] if obj.get("volunteering") is not None else None,
            "object": obj.get("object")
        })
        return _obj


