# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BrowseSalesLeadListRequest(BaseModel):
    """
    BrowseSalesLeadListRequest
    """ # noqa: E501
    spotlight: Optional[StrictStr] = Field(default=None, description="Smart filter to help you prioritize leads.")
    sort_by: Optional[StrictStr] = Field(default='DATE_ADDED', description="The sort method.")
    sort_order: Optional[StrictStr] = Field(default='DESCENDING', description="The sort order.")
    __properties: ClassVar[List[str]] = ["spotlight", "sort_by", "sort_order"]

    @field_validator('spotlight')
    def spotlight_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['RECENT_POSITION_CHANGE', 'RECENTLY_POSTED_ON_LINKEDIN', 'FOLLOW_YOUR_COMPANY', 'SHARE_EXPERIENCE']):
            raise ValueError("must be one of enum values ('RECENT_POSITION_CHANGE', 'RECENTLY_POSTED_ON_LINKEDIN', 'FOLLOW_YOUR_COMPANY', 'SHARE_EXPERIENCE')")
        return value

    @field_validator('sort_by')
    def sort_by_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DATE_ADDED', 'ACCOUNT', 'NAME', 'OUTREACH_ACTIVITY']):
            raise ValueError("must be one of enum values ('DATE_ADDED', 'ACCOUNT', 'NAME', 'OUTREACH_ACTIVITY')")
        return value

    @field_validator('sort_order')
    def sort_order_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ASCENDING', 'DESCENDING']):
            raise ValueError("must be one of enum values ('ASCENDING', 'DESCENDING')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrowseSalesLeadListRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrowseSalesLeadListRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "spotlight": obj.get("spotlight"),
            "sort_by": obj.get("sort_by") if obj.get("sort_by") is not None else 'DATE_ADDED',
            "sort_order": obj.get("sort_order") if obj.get("sort_order") is not None else 'DESCENDING'
        })
        return _obj


