# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.create_post_request_specifics import CreatePostRequestSpecifics
from unipile.models.send_email_request_attachments_inner import SendEmailRequestAttachmentsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePostRequest(BaseModel):
    """
    CreatePostRequest
    """ # noqa: E501
    text: StrictStr = Field(description="Textual content of the post. User mentions can be added by inserting an @ followed by the ID or public identifier of the user (example: @JohnDoe).")
    attachments: Optional[List[SendEmailRequestAttachmentsInner]] = Field(default=None, description="The list of files to appear in the post.")
    can_read: Optional[StrictStr] = Field(default='anyone', description="The visibility level for the new post (if supported by the provider).           - `anyone` is visible to anyone.           - `relations_only` is visible only to the user's relations.")
    can_comment: Optional[StrictStr] = Field(default='anyone', description="The comment control level for the new post (if supported by the provider).           - `anyone` anyone can comment.           - `relations_only` only to the user's relations can comment.           - `no_one` no one can comment.")
    quoted_post_id: Optional[StrictStr] = Field(default=None, description="The ID of a Post to be quoted. For a simple repost without commentary, leave `text` as an empty string.")
    post_as: Optional[StrictStr] = Field(default=None, description="The ID of the User on whose behalf the post should be published (if supported by the provider).")
    specifics: Optional[CreatePostRequestSpecifics] = None
    __properties: ClassVar[List[str]] = ["text", "attachments", "can_read", "can_comment", "quoted_post_id", "post_as", "specifics"]

    @field_validator('can_read')
    def can_read_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['anyone', 'relations_only']):
            raise ValueError("must be one of enum values ('anyone', 'relations_only')")
        return value

    @field_validator('can_comment')
    def can_comment_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['anyone', 'relations_only', 'no_one']):
            raise ValueError("must be one of enum values ('anyone', 'relations_only', 'no_one')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of specifics
        if self.specifics:
            _dict['specifics'] = self.specifics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "attachments": [SendEmailRequestAttachmentsInner.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "can_read": obj.get("can_read") if obj.get("can_read") is not None else 'anyone',
            "can_comment": obj.get("can_comment") if obj.get("can_comment") is not None else 'anyone',
            "quoted_post_id": obj.get("quoted_post_id"),
            "post_as": obj.get("post_as"),
            "specifics": CreatePostRequestSpecifics.from_dict(obj["specifics"]) if obj.get("specifics") is not None else None
        })
        return _obj


