# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from unipile.models.full_profile_certifications_inner import FullProfileCertificationsInner
from unipile.models.full_profile_education_inner import FullProfileEducationInner
from unipile.models.full_profile_projects_inner import FullProfileProjectsInner
from unipile.models.full_profile_skills_inner import FullProfileSkillsInner
from unipile.models.linked_in_languages_inner import LinkedInLanguagesInner
from unipile.models.linked_in_recommendations_received_inner import LinkedInRecommendationsReceivedInner
from unipile.models.linked_in_volunteer_experience_inner import LinkedInVolunteerExperienceInner
from unipile.models.partial_profile_hiring_project import PartialProfileHiringProject
from unipile.models.partial_profile_work_experience_inner import PartialProfileWorkExperienceInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FullProfile1(BaseModel):
    """
    FullProfile1
    """ # noqa: E501
    object: StrictStr
    id: StrictStr = Field(description="The ID of the user.")
    member_id: Optional[StrictStr] = Field(default=None, description="The LinkedIn internal member ID of the user.")
    display_name: StrictStr = Field(description="The display name of the User.")
    public_identifier: Optional[StrictStr] = Field(default=None, description="The public identifier of the User.")
    profile_url: Optional[StrictStr] = Field(default=None, description="The profile URL of the User.")
    public_picture_url: Optional[StrictStr] = Field(default=None, description="The public picture URL of the User.")
    public_picture_url_large: Optional[StrictStr] = Field(default=None, description="The public picture URL of the User in large size.")
    relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of relations of the User.")
    location: Optional[StrictStr] = Field(default=None, description="The location of the User.")
    headline: Optional[StrictStr] = Field(default=None, description="The headline of the User.")
    network_distance: StrictStr = Field(description="Network distance to a User.       `SELF`: Yourself.       `FIRST_DEGREE`: 1st degree connection.       `SECOND_DEGREE`: 2nd degree connection (connection of a 1st degree).       `THIRD_DEGREE`: 3rd degree connection (connection of a 2nd degree).       `OUT_OF_NETWORK`: Unreachable user.'")
    can_send_inmail: Optional[StrictBool] = Field(default=None, description="Whether it is possible to send an inMail to this User.")
    product: StrictStr
    visibility: StrictStr = Field(description="Indidates that you have access to the full profile of this User.")
    candidate_id: StrictStr = Field(description="The candidate ID of the User.")
    is_hidden_candidate: StrictBool = Field(description="Whether the User has been set as hidden candidate.")
    hiring_project: Optional[PartialProfileHiringProject] = None
    work_experience: List[PartialProfileWorkExperienceInner] = Field(description="A list of the User's work experiences.")
    industry: StrictStr = Field(description="The industry to which the User belongs.")
    followers_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of the followers of the User.")
    skills: List[FullProfileSkillsInner] = Field(description="A list of skills.")
    summary: Optional[StrictStr] = Field(default=None, description="The summary of the User.")
    emails: Optional[List[StrictStr]] = None
    phone_numbers: Optional[List[StrictStr]] = None
    education: List[FullProfileEducationInner]
    languages: List[LinkedInLanguagesInner]
    certifications: List[FullProfileCertificationsInner]
    projects: List[FullProfileProjectsInner]
    volunteering: List[LinkedInVolunteerExperienceInner]
    recommendations: List[LinkedInRecommendationsReceivedInner]
    __properties: ClassVar[List[str]] = ["object", "id", "member_id", "display_name", "public_identifier", "profile_url", "public_picture_url", "public_picture_url_large", "relations_count", "location", "headline", "network_distance", "can_send_inmail", "product", "visibility", "candidate_id", "is_hidden_candidate", "hiring_project", "work_experience", "industry", "followers_count", "skills", "summary", "emails", "phone_numbers", "education", "languages", "certifications", "projects", "volunteering", "recommendations"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PeopleSearchResult']):
            raise ValueError("must be one of enum values ('PeopleSearchResult')")
        return value

    @field_validator('network_distance')
    def network_distance_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SELF', 'FIRST_DEGREE', 'SECOND_DEGREE', 'THIRD_DEGREE', 'OUT_OF_NETWORK']):
            raise ValueError("must be one of enum values ('SELF', 'FIRST_DEGREE', 'SECOND_DEGREE', 'THIRD_DEGREE', 'OUT_OF_NETWORK')")
        return value

    @field_validator('product')
    def product_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['recruiter']):
            raise ValueError("must be one of enum values ('recruiter')")
        return value

    @field_validator('visibility')
    def visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['full']):
            raise ValueError("must be one of enum values ('full')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FullProfile1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hiring_project
        if self.hiring_project:
            _dict['hiring_project'] = self.hiring_project.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in work_experience (list)
        _items = []
        if self.work_experience:
            for _item_work_experience in self.work_experience:
                if _item_work_experience:
                    _items.append(_item_work_experience.to_dict())
            _dict['work_experience'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in skills (list)
        _items = []
        if self.skills:
            for _item_skills in self.skills:
                if _item_skills:
                    _items.append(_item_skills.to_dict())
            _dict['skills'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in education (list)
        _items = []
        if self.education:
            for _item_education in self.education:
                if _item_education:
                    _items.append(_item_education.to_dict())
            _dict['education'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in languages (list)
        _items = []
        if self.languages:
            for _item_languages in self.languages:
                if _item_languages:
                    _items.append(_item_languages.to_dict())
            _dict['languages'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in certifications (list)
        _items = []
        if self.certifications:
            for _item_certifications in self.certifications:
                if _item_certifications:
                    _items.append(_item_certifications.to_dict())
            _dict['certifications'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in projects (list)
        _items = []
        if self.projects:
            for _item_projects in self.projects:
                if _item_projects:
                    _items.append(_item_projects.to_dict())
            _dict['projects'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in volunteering (list)
        _items = []
        if self.volunteering:
            for _item_volunteering in self.volunteering:
                if _item_volunteering:
                    _items.append(_item_volunteering.to_dict())
            _dict['volunteering'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recommendations (list)
        _items = []
        if self.recommendations:
            for _item_recommendations in self.recommendations:
                if _item_recommendations:
                    _items.append(_item_recommendations.to_dict())
            _dict['recommendations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FullProfile1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "member_id": obj.get("member_id"),
            "display_name": obj.get("display_name"),
            "public_identifier": obj.get("public_identifier"),
            "profile_url": obj.get("profile_url"),
            "public_picture_url": obj.get("public_picture_url"),
            "public_picture_url_large": obj.get("public_picture_url_large"),
            "relations_count": obj.get("relations_count"),
            "location": obj.get("location"),
            "headline": obj.get("headline"),
            "network_distance": obj.get("network_distance"),
            "can_send_inmail": obj.get("can_send_inmail"),
            "product": obj.get("product"),
            "visibility": obj.get("visibility"),
            "candidate_id": obj.get("candidate_id"),
            "is_hidden_candidate": obj.get("is_hidden_candidate"),
            "hiring_project": PartialProfileHiringProject.from_dict(obj["hiring_project"]) if obj.get("hiring_project") is not None else None,
            "work_experience": [PartialProfileWorkExperienceInner.from_dict(_item) for _item in obj["work_experience"]] if obj.get("work_experience") is not None else None,
            "industry": obj.get("industry"),
            "followers_count": obj.get("followers_count"),
            "skills": [FullProfileSkillsInner.from_dict(_item) for _item in obj["skills"]] if obj.get("skills") is not None else None,
            "summary": obj.get("summary"),
            "emails": obj.get("emails"),
            "phone_numbers": obj.get("phone_numbers"),
            "education": [FullProfileEducationInner.from_dict(_item) for _item in obj["education"]] if obj.get("education") is not None else None,
            "languages": [LinkedInLanguagesInner.from_dict(_item) for _item in obj["languages"]] if obj.get("languages") is not None else None,
            "certifications": [FullProfileCertificationsInner.from_dict(_item) for _item in obj["certifications"]] if obj.get("certifications") is not None else None,
            "projects": [FullProfileProjectsInner.from_dict(_item) for _item in obj["projects"]] if obj.get("projects") is not None else None,
            "volunteering": [LinkedInVolunteerExperienceInner.from_dict(_item) for _item in obj["volunteering"]] if obj.get("volunteering") is not None else None,
            "recommendations": [LinkedInRecommendationsReceivedInner.from_dict(_item) for _item in obj["recommendations"]] if obj.get("recommendations") is not None else None
        })
        return _obj


