# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.get_user_profile200_response_specifics_all_of_any_of_projects_inner_contributors_inner import GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner
from typing import Optional, Set
from typing_extensions import Self

class FullProfileProjectsInner(BaseModel):
    """
    FullProfileProjectsInner
    """ # noqa: E501
    name: StrictStr = Field(description="Name of the project.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the project.")
    contributors: List[GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner] = Field(description="Contributors to the project.")
    skills: Optional[List[StrictStr]] = Field(default=None, description="Skills related to the project.")
    skills_preview: Optional[StrictStr] = Field(default=None, description="Insight of the skills related to the project.")
    started_on: Optional[StrictStr] = Field(default=None, description="Start date of the project in MM/DD/YYYY format.")
    ended_on: Optional[StrictStr] = Field(default=None, description="End date of the project in MM/DD/YYYY format.")
    __properties: ClassVar[List[str]] = ["name", "description", "contributors", "skills", "skills_preview", "started_on", "ended_on"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FullProfileProjectsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contributors (list)
        _items = []
        if self.contributors:
            for _item_contributors in self.contributors:
                if _item_contributors:
                    _items.append(_item_contributors.to_dict())
            _dict['contributors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FullProfileProjectsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "contributors": [GetUserProfile200ResponseSpecificsAllOfAnyOfProjectsInnerContributorsInner.from_dict(_item) for _item in obj["contributors"]] if obj.get("contributors") is not None else None,
            "skills": obj.get("skills"),
            "skills_preview": obj.get("skills_preview"),
            "started_on": obj.get("started_on"),
            "ended_on": obj.get("ended_on")
        })
        return _obj


