# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from unipile.models.get_email_contacts_list200_response_data_inner_social_handles import GetEmailContactsList200ResponseDataInnerSocialHandles
from unipile.models.get_user_profile200_response_specifics import GetUserProfile200ResponseSpecifics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetUserProfile200Response(BaseModel):
    """
    GetUserProfile200Response
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the user for the provider. Usually an internal identifier used by the API only.")
    object: StrictStr
    type: StrictStr = Field(description="Type of the user       - `individual` is an individual user.       - `organization` is an organization / business entity.       - `other` is an other type of entity.")
    public_identifier: Optional[StrictStr] = Field(default=None, description="Public identifier of the user for the provider. Usually a shareable tag visible in urls and profiles. ")
    display_name: StrictStr = Field(description="Display name of the user.")
    profile_url: Optional[StrictStr] = Field(default=None, description="Public url to the profile of the user.")
    public_picture_url: Optional[StrictStr] = Field(default=None, description="Public url to the profile picture of the user.")
    private_picture_download_url: Optional[StrictStr] = Field(default=None, description="Private url to download the profile picture of the user. This url require authentication.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the user.")
    background_picture_url: Optional[StrictStr] = Field(default=None, description="URL of the user's background / banner picture.")
    public_picture_url_large: Optional[StrictStr] = Field(default=None, description="URL of the user's public picture in large size.")
    first_name: Optional[StrictStr] = Field(default=None, description="First name of the user.")
    last_name: Optional[StrictStr] = Field(default=None, description="Last name of the user.")
    birth_date: Optional[StrictStr] = Field(default=None, description="Birth date of the user.")
    addresses: Optional[List[Optional[StrictStr]]] = Field(default=None, description="List of user addresses.")
    emails: Optional[List[StrictStr]] = Field(default=None, description="List of user email addresses.")
    phone_numbers: Optional[List[StrictStr]] = Field(default=None, description="List of user phone numbers.")
    created_at: Optional[StrictStr] = Field(default=None, description="Date and time when the user account was created on the provider.")
    bio: Optional[StrictStr] = Field(default=None, description="Biography of the user.")
    location: Optional[StrictStr] = Field(default=None, description="Location of the user.")
    muted_until: Optional[StrictStr] = Field(default=None, description="Date and time until when the user is muted. ")
    following: Optional[StrictBool] = Field(default=None, description="Whether the user is followed by the current user.")
    followers_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of followers of the user.")
    following_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of users followed by the user.")
    relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of relations of the user.")
    shared_relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of users that have a relation with the given profile and with the account owner.")
    shared_followers_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of following users that follows the given profile.")
    is_blocked: StrictBool = Field(description="Whether the user is blocked by the current user.")
    provider: StrictStr = Field(description="The provider's of the Account.     - `mock` is mock.     - `whatsapp` is WhatsApp.     - `linkedin` is LinkedIn.     - `instagram` is Instagram.     - `google` is Google.     - `outlook` is Outlook.     - `telegram` is Telegram.     - `imap` is IMAP.")
    specifics: GetUserProfile200ResponseSpecifics
    social_handles: Optional[GetEmailContactsList200ResponseDataInnerSocialHandles] = None
    websites: Optional[List[StrictStr]] = Field(default=None, description="List of user websites.")
    __properties: ClassVar[List[str]] = ["id", "object", "type", "public_identifier", "display_name", "profile_url", "public_picture_url", "private_picture_download_url", "description", "background_picture_url", "public_picture_url_large", "first_name", "last_name", "birth_date", "addresses", "emails", "phone_numbers", "created_at", "bio", "location", "muted_until", "following", "followers_count", "following_count", "relations_count", "shared_relations_count", "shared_followers_count", "is_blocked", "provider", "specifics", "social_handles", "websites"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['UserProfile']):
            raise ValueError("must be one of enum values ('UserProfile')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['individual', 'organization', 'other']):
            raise ValueError("must be one of enum values ('individual', 'organization', 'other')")
        return value

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['mock', 'whatsapp', 'linkedin', 'google', 'outlook', 'imap', 'telegram', 'instagram']):
            raise ValueError("must be one of enum values ('mock', 'whatsapp', 'linkedin', 'google', 'outlook', 'imap', 'telegram', 'instagram')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUserProfile200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of specifics
        if self.specifics:
            _dict['specifics'] = self.specifics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of social_handles
        if self.social_handles:
            _dict['social_handles'] = self.social_handles.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUserProfile200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "type": obj.get("type"),
            "public_identifier": obj.get("public_identifier"),
            "display_name": obj.get("display_name"),
            "profile_url": obj.get("profile_url"),
            "public_picture_url": obj.get("public_picture_url"),
            "private_picture_download_url": obj.get("private_picture_download_url"),
            "description": obj.get("description"),
            "background_picture_url": obj.get("background_picture_url"),
            "public_picture_url_large": obj.get("public_picture_url_large"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "birth_date": obj.get("birth_date"),
            "addresses": obj.get("addresses"),
            "emails": obj.get("emails"),
            "phone_numbers": obj.get("phone_numbers"),
            "created_at": obj.get("created_at"),
            "bio": obj.get("bio"),
            "location": obj.get("location"),
            "muted_until": obj.get("muted_until"),
            "following": obj.get("following"),
            "followers_count": obj.get("followers_count"),
            "following_count": obj.get("following_count"),
            "relations_count": obj.get("relations_count"),
            "shared_relations_count": obj.get("shared_relations_count"),
            "shared_followers_count": obj.get("shared_followers_count"),
            "is_blocked": obj.get("is_blocked"),
            "provider": obj.get("provider"),
            "specifics": GetUserProfile200ResponseSpecifics.from_dict(obj["specifics"]) if obj.get("specifics") is not None else None,
            "social_handles": GetEmailContactsList200ResponseDataInnerSocialHandles.from_dict(obj["social_handles"]) if obj.get("social_handles") is not None else None,
            "websites": obj.get("websites")
        })
        return _obj


