# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from unipile.models.get_messages_list200_response_data_inner_reactions_counter_inner import GetMessagesList200ResponseDataInnerReactionsCounterInner
from unipile.models.get_post_comments_list200_response_data_inner_author import GetPostCommentsList200ResponseDataInnerAuthor
from typing import Optional, Set
from typing_extensions import Self

class GetPostCommentsList200ResponseDataInner(BaseModel):
    """
    GetPostCommentsList200ResponseDataInner
    """ # noqa: E501
    object: StrictStr
    id: StrictStr = Field(description="The ID of the comment.")
    thread_id: Optional[StrictStr] = Field(default=None, description="The ID of the thread if this is a reply to another comment.")
    author: GetPostCommentsList200ResponseDataInnerAuthor
    created_at: StrictStr = Field(description="The creation date of the comment. Uses ISO 8601 UTC datetime (YYYY-MM-DDTHH:MM:SS.sssZ).")
    text: StrictStr = Field(description="The text content of the comment.")
    is_sender: StrictBool = Field(description="Is the current user the sender of the comment.")
    can_reply: StrictBool = Field(description="Whether the current user can reply to the comment or not.")
    can_react: StrictBool = Field(description="Whether the current user can react to the comment or not.")
    reply_counter: Union[StrictFloat, StrictInt] = Field(description="The number of replies to the comment.")
    reactions_counter: List[GetMessagesList200ResponseDataInnerReactionsCounterInner] = Field(description="The number of reactions to the element")
    __properties: ClassVar[List[str]] = ["object", "id", "thread_id", "author", "created_at", "text", "is_sender", "can_reply", "can_react", "reply_counter", "reactions_counter"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Comment']):
            raise ValueError("must be one of enum values ('Comment')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetPostCommentsList200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reactions_counter (list)
        _items = []
        if self.reactions_counter:
            for _item_reactions_counter in self.reactions_counter:
                if _item_reactions_counter:
                    _items.append(_item_reactions_counter.to_dict())
            _dict['reactions_counter'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetPostCommentsList200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "thread_id": obj.get("thread_id"),
            "author": GetPostCommentsList200ResponseDataInnerAuthor.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "created_at": obj.get("created_at"),
            "text": obj.get("text"),
            "is_sender": obj.get("is_sender"),
            "can_reply": obj.get("can_reply"),
            "can_react": obj.get("can_react"),
            "reply_counter": obj.get("reply_counter"),
            "reactions_counter": [GetMessagesList200ResponseDataInnerReactionsCounterInner.from_dict(_item) for _item in obj["reactions_counter"]] if obj.get("reactions_counter") is not None else None
        })
        return _obj


