# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetPostsList200ResponseDataInnerAnalytics(BaseModel):
    """
    Analytics data of the post.
    """ # noqa: E501
    impressions_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of impressions of the post.")
    engagements_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of engagements of the post.")
    engagement_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The engagement rate of the post.")
    clicks_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of clicks of the post.")
    clickthrough_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The clickthrough rate of the post.")
    page_viewers_from_this_post_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of page viewers from this post.")
    followers_gained_from_this_post_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of followers gained from this post.")
    users_reached_counter: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of users reached from this post.")
    __properties: ClassVar[List[str]] = ["impressions_counter", "engagements_counter", "engagement_rate", "clicks_counter", "clickthrough_rate", "page_viewers_from_this_post_counter", "followers_gained_from_this_post_counter", "users_reached_counter"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetPostsList200ResponseDataInnerAnalytics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetPostsList200ResponseDataInnerAnalytics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "impressions_counter": obj.get("impressions_counter"),
            "engagements_counter": obj.get("engagements_counter"),
            "engagement_rate": obj.get("engagement_rate"),
            "clicks_counter": obj.get("clicks_counter"),
            "clickthrough_rate": obj.get("clickthrough_rate"),
            "page_viewers_from_this_post_counter": obj.get("page_viewers_from_this_post_counter"),
            "followers_gained_from_this_post_counter": obj.get("followers_gained_from_this_post_counter"),
            "users_reached_counter": obj.get("users_reached_counter")
        })
        return _obj


