# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.get_recruiter_hiring_project200_response_metadata import GetRecruiterHiringProject200ResponseMetadata
from unipile.models.get_recruiter_hiring_project_list200_response_data_inner_owner import GetRecruiterHiringProjectList200ResponseDataInnerOwner
from unipile.models.get_recruiter_hiring_project_list200_response_data_inner_pipeline import GetRecruiterHiringProjectList200ResponseDataInnerPipeline
from unipile.models.get_recruiter_hiring_project_list200_response_data_inner_talent_pool import GetRecruiterHiringProjectList200ResponseDataInnerTalentPool
from typing import Optional, Set
from typing_extensions import Self

class GetRecruiterHiringProject200Response(BaseModel):
    """
    GetRecruiterHiringProject200Response
    """ # noqa: E501
    object: StrictStr
    id: StrictStr = Field(description="The ID of the Project.")
    name: StrictStr = Field(description="The name of the Project.")
    readonly: StrictBool = Field(description="Whether the Project is read only.")
    created_at: StrictStr = Field(description="The date on which the Project was created. Uses ISO 8601 UTC datetime (YYYY-MM-DDTHH:MM:SS.sssZ).")
    last_accessed_at: Optional[StrictStr] = Field(default=None, description="The date on which the Project was last accessed. Uses ISO 8601 UTC datetime (YYYY-MM-DDTHH:MM:SS.sssZ).")
    last_modified_at: StrictStr = Field(description="The date on which the Project was last modified. Uses ISO 8601 UTC datetime (YYYY-MM-DDTHH:MM:SS.sssZ).")
    visibility: StrictStr = Field(description="The visibility level of the Project.")
    owner: GetRecruiterHiringProjectList200ResponseDataInnerOwner
    metadata: GetRecruiterHiringProject200ResponseMetadata
    talent_pool: GetRecruiterHiringProjectList200ResponseDataInnerTalentPool
    pipeline: GetRecruiterHiringProjectList200ResponseDataInnerPipeline
    __properties: ClassVar[List[str]] = ["object", "id", "name", "readonly", "created_at", "last_accessed_at", "last_modified_at", "visibility", "owner", "metadata", "talent_pool", "pipeline"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['HiringProject']):
            raise ValueError("must be one of enum values ('HiringProject')")
        return value

    @field_validator('visibility')
    def visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PRIVATE', 'SHARED']):
            raise ValueError("must be one of enum values ('PRIVATE', 'SHARED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRecruiterHiringProject200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of talent_pool
        if self.talent_pool:
            _dict['talent_pool'] = self.talent_pool.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pipeline
        if self.pipeline:
            _dict['pipeline'] = self.pipeline.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRecruiterHiringProject200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "readonly": obj.get("readonly"),
            "created_at": obj.get("created_at"),
            "last_accessed_at": obj.get("last_accessed_at"),
            "last_modified_at": obj.get("last_modified_at"),
            "visibility": obj.get("visibility"),
            "owner": GetRecruiterHiringProjectList200ResponseDataInnerOwner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "metadata": GetRecruiterHiringProject200ResponseMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "talent_pool": GetRecruiterHiringProjectList200ResponseDataInnerTalentPool.from_dict(obj["talent_pool"]) if obj.get("talent_pool") is not None else None,
            "pipeline": GetRecruiterHiringProjectList200ResponseDataInnerPipeline.from_dict(obj["pipeline"]) if obj.get("pipeline") is not None else None
        })
        return _obj


