# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from unipile.models.get_recruiter_job_posting_budget200_response_promoted_daily import GetRecruiterJobPostingBudget200ResponsePromotedDaily
from typing import Optional, Set
from typing_extensions import Self

class GetRecruiterJobPostingBudget200ResponsePromoted(BaseModel):
    """
    GetRecruiterJobPostingBudget200ResponsePromoted
    """ # noqa: E501
    currency: StrictStr = Field(description="The Budget currency.")
    daily: GetRecruiterJobPostingBudget200ResponsePromotedDaily
    total: GetRecruiterJobPostingBudget200ResponsePromotedDaily
    estimated_daily_applicants_count: Union[StrictFloat, StrictInt] = Field(description="The estimated number of applicants per day.")
    __properties: ClassVar[List[str]] = ["currency", "daily", "total", "estimated_daily_applicants_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRecruiterJobPostingBudget200ResponsePromoted from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of daily
        if self.daily:
            _dict['daily'] = self.daily.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total
        if self.total:
            _dict['total'] = self.total.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRecruiterJobPostingBudget200ResponsePromoted from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency": obj.get("currency"),
            "daily": GetRecruiterJobPostingBudget200ResponsePromotedDaily.from_dict(obj["daily"]) if obj.get("daily") is not None else None,
            "total": GetRecruiterJobPostingBudget200ResponsePromotedDaily.from_dict(obj["total"]) if obj.get("total") is not None else None,
            "estimated_daily_applicants_count": obj.get("estimated_daily_applicants_count")
        })
        return _obj


