# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from unipile.models.get_recruiter_hiring_project_list200_response_data_inner_pipeline_stages_inner import GetRecruiterHiringProjectList200ResponseDataInnerPipelineStagesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetRecruiterHiringProjectList200ResponseDataInnerPipeline(BaseModel):
    """
    The pipeline of the Project.
    """ # noqa: E501
    enabled: StrictBool = Field(description="Whether the pipeline is active.")
    name: StrictStr = Field(description="The name of the Pipeline.")
    description: StrictStr = Field(description="The description of the Pipeline.")
    created_at: StrictStr = Field(description="The date on which the Pipeline was created. Uses ISO 8601 UTC datetime (YYYY-MM-DDTHH:MM:SS.sssZ).")
    last_modified_at: StrictStr = Field(description="The date on which the Pipeline was last modified. Uses ISO 8601 UTC datetime (YYYY-MM-DDTHH:MM:SS.sssZ).")
    stages: List[GetRecruiterHiringProjectList200ResponseDataInnerPipelineStagesInner] = Field(description="A list of stages that make up the Pipeline.")
    __properties: ClassVar[List[str]] = ["enabled", "name", "description", "created_at", "last_modified_at", "stages"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRecruiterHiringProjectList200ResponseDataInnerPipeline from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in stages (list)
        _items = []
        if self.stages:
            for _item_stages in self.stages:
                if _item_stages:
                    _items.append(_item_stages.to_dict())
            _dict['stages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRecruiterHiringProjectList200ResponseDataInnerPipeline from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enabled": obj.get("enabled"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "last_modified_at": obj.get("last_modified_at"),
            "stages": [GetRecruiterHiringProjectList200ResponseDataInnerPipelineStagesInner.from_dict(_item) for _item in obj["stages"]] if obj.get("stages") is not None else None
        })
        return _obj


