# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.get_user_profile200_response_specifics_all_of_any_of_education_inner_school import GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInnerSchool
from typing import Optional, Set
from typing_extensions import Self

class GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInner(BaseModel):
    """
    GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Id of the education entry.")
    school: GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInnerSchool
    degree: Optional[StrictStr] = Field(default=None, description="Name of the degree.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the education.")
    activities: Optional[StrictStr] = Field(default=None, description="Activities carried out during education.")
    skills: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Skills acquired through training.")
    skills_preview: Optional[StrictStr] = Field(default=None, description="Insight of the skills acquired through training.")
    grade: Optional[StrictStr] = Field(default=None, description="Reached academic level of the education.")
    fields_of_study: Optional[List[Optional[StrictStr]]] = Field(default=None, description="Fields of study of the education.")
    started_on: Optional[StrictStr] = Field(default=None, description="Start date of the education in MM/DD/YYYY format.")
    ended_on: Optional[StrictStr] = Field(default=None, description="End date of the education in MM/DD/YYYY format.")
    __properties: ClassVar[List[str]] = ["id", "school", "degree", "description", "activities", "skills", "skills_preview", "grade", "fields_of_study", "started_on", "ended_on"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of school
        if self.school:
            _dict['school'] = self.school.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "school": GetUserProfile200ResponseSpecificsAllOfAnyOfEducationInnerSchool.from_dict(obj["school"]) if obj.get("school") is not None else None,
            "degree": obj.get("degree"),
            "description": obj.get("description"),
            "activities": obj.get("activities"),
            "skills": obj.get("skills"),
            "skills_preview": obj.get("skills_preview"),
            "grade": obj.get("grade"),
            "fields_of_study": obj.get("fields_of_study"),
            "started_on": obj.get("started_on"),
            "ended_on": obj.get("ended_on")
        })
        return _obj


