# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.32.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.linked_in1_interests_companies_inner import LinkedIn1InterestsCompaniesInner
from unipile.models.linked_in1_interests_groups_inner import LinkedIn1InterestsGroupsInner
from unipile.models.linked_in1_interests_newsletters_inner import LinkedIn1InterestsNewslettersInner
from unipile.models.linked_in1_interests_schools_inner import LinkedIn1InterestsSchoolsInner
from unipile.models.linked_in1_interests_top_voices_inner import LinkedIn1InterestsTopVoicesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LinkedIn1Interests(BaseModel):
    """
    The user's interests.
    """ # noqa: E501
    top_voices: Optional[List[LinkedIn1InterestsTopVoicesInner]] = Field(default=None, description="A collection of Top voice User profiles.")
    companies: Optional[List[LinkedIn1InterestsCompaniesInner]] = Field(default=None, description="A collection of Companies.")
    schools: Optional[List[LinkedIn1InterestsSchoolsInner]] = Field(default=None, description="A collection of Schools.")
    newsletters: Optional[List[LinkedIn1InterestsNewslettersInner]] = Field(default=None, description="A collection of Newsletters.")
    groups: Optional[List[LinkedIn1InterestsGroupsInner]] = Field(default=None, description="A collection of Groups.")
    __properties: ClassVar[List[str]] = ["top_voices", "companies", "schools", "newsletters", "groups"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LinkedIn1Interests from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in top_voices (list)
        _items = []
        if self.top_voices:
            for _item_top_voices in self.top_voices:
                _items.append(_item_top_voices.to_dict() if _item_top_voices is not None else None)
            _dict['top_voices'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in companies (list)
        _items = []
        if self.companies:
            for _item_companies in self.companies:
                _items.append(_item_companies.to_dict() if _item_companies is not None else None)
            _dict['companies'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in schools (list)
        _items = []
        if self.schools:
            for _item_schools in self.schools:
                _items.append(_item_schools.to_dict() if _item_schools is not None else None)
            _dict['schools'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in newsletters (list)
        _items = []
        if self.newsletters:
            for _item_newsletters in self.newsletters:
                _items.append(_item_newsletters.to_dict() if _item_newsletters is not None else None)
            _dict['newsletters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                _items.append(_item_groups.to_dict() if _item_groups is not None else None)
            _dict['groups'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LinkedIn1Interests from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "top_voices": [LinkedIn1InterestsTopVoicesInner.from_dict(_item) for _item in obj["top_voices"]] if obj.get("top_voices") is not None else None,
            "companies": [LinkedIn1InterestsCompaniesInner.from_dict(_item) for _item in obj["companies"]] if obj.get("companies") is not None else None,
            "schools": [LinkedIn1InterestsSchoolsInner.from_dict(_item) for _item in obj["schools"]] if obj.get("schools") is not None else None,
            "newsletters": [LinkedIn1InterestsNewslettersInner.from_dict(_item) for _item in obj["newsletters"]] if obj.get("newsletters") is not None else None,
            "groups": [LinkedIn1InterestsGroupsInner.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None
        })
        return _obj


