# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.linked_in_recommendations_received_inner_user import LinkedInRecommendationsReceivedInnerUser
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LinkedInRecommendationsReceivedInner(BaseModel):
    """
    LinkedInRecommendationsReceivedInner
    """ # noqa: E501
    caption: Optional[StrictStr] = Field(default=None, description="Recommendation details, including date and actors relationship.")
    created_on: Optional[StrictStr] = Field(default=None, description="Creation date of the recommendation.")
    text: StrictStr = Field(description="Content of the recommendation.")
    user: Optional[LinkedInRecommendationsReceivedInnerUser]
    __properties: ClassVar[List[str]] = ["caption", "created_on", "text", "user"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LinkedInRecommendationsReceivedInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LinkedInRecommendationsReceivedInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "caption": obj.get("caption"),
            "created_on": obj.get("created_on"),
            "text": obj.get("text"),
            "user": LinkedInRecommendationsReceivedInnerUser.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


