# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.linked_in_recruiting_profile_events_inner import LinkedInRecruitingProfileEventsInner
from unipile.models.linked_in_recruiting_profile_notes_inner import LinkedInRecruitingProfileNotesInner
from unipile.models.linked_in_recruiting_profile_tags_inner import LinkedInRecruitingProfileTagsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LinkedInRecruitingProfile(BaseModel):
    """
    LinkedInRecruitingProfile
    """ # noqa: E501
    events: Optional[List[LinkedInRecruitingProfileEventsInner]] = Field(default=None, description="A list of events related to the user.")
    notes: List[LinkedInRecruitingProfileNotesInner] = Field(description="A list of notes about the user.")
    tags: List[LinkedInRecruitingProfileTagsInner] = Field(description="A list of tags about the user.")
    __properties: ClassVar[List[str]] = ["events", "notes", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LinkedInRecruitingProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in notes (list)
        _items = []
        if self.notes:
            for _item_notes in self.notes:
                if _item_notes:
                    _items.append(_item_notes.to_dict())
            _dict['notes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LinkedInRecruitingProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "events": [LinkedInRecruitingProfileEventsInner.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "notes": [LinkedInRecruitingProfileNotesInner.from_dict(_item) for _item in obj["notes"]] if obj.get("notes") is not None else None,
            "tags": [LinkedInRecruitingProfileTagsInner.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj


