# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class ListClassicUserJobPostings200ResponseDataInner(BaseModel):
    """
    ListClassicUserJobPostings200ResponseDataInner
    """ # noqa: E501
    object: StrictStr
    product: StrictStr
    id: StrictStr = Field(description="The ID of the Job posting.")
    title: StrictStr = Field(description="The title of the Job posting.")
    company: StrictStr = Field(description="The company that published the Job posting.")
    location: StrictStr = Field(description="The location of the Job posting.")
    state: StrictStr = Field(description="The state of the Job posting.")
    applications_count: Union[StrictFloat, StrictInt] = Field(description="The number of applications for this job posting.")
    __properties: ClassVar[List[str]] = ["object", "product", "id", "title", "company", "location", "state", "applications_count"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['JobPostingListItem']):
            raise ValueError("must be one of enum values ('JobPostingListItem')")
        return value

    @field_validator('product')
    def product_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['classic']):
            raise ValueError("must be one of enum values ('classic')")
        return value

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DRAFT', 'LISTED', 'CLOSED', 'REVIEW', 'SUSPENDED']):
            raise ValueError("must be one of enum values ('DRAFT', 'LISTED', 'CLOSED', 'REVIEW', 'SUSPENDED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListClassicUserJobPostings200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListClassicUserJobPostings200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "product": obj.get("product"),
            "id": obj.get("id"),
            "title": obj.get("title"),
            "company": obj.get("company"),
            "location": obj.get("location"),
            "state": obj.get("state"),
            "applications_count": obj.get("applications_count")
        })
        return _obj


