# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from unipile.models.linked_in_certifications_inner_organization import LinkedInCertificationsInnerOrganization
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PartialProfileWorkExperienceInner(BaseModel):
    """
    PartialProfileWorkExperienceInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Id of the work experience entry.")
    company: LinkedInCertificationsInnerOrganization
    job_title: StrictStr = Field(description="Job title of the experience.")
    started_on: Optional[StrictStr] = Field(default=None, description="Start date of the experience in MM/DD/YYYY format.")
    ended_on: Optional[StrictStr] = Field(default=None, description="End date of the experience in MM/DD/YYYY format.")
    location: Optional[StrictStr] = Field(default=None, description="Location of the experience.")
    description: Optional[StrictStr] = Field(default=None, description="Description of the experience.")
    employment_type: Optional[StrictStr] = Field(default=None, description="Employment type of the experience.")
    workplace_type: Optional[StrictStr] = Field(default=None, description="Workplace type of the experience.")
    skills: Optional[List[StrictStr]] = Field(default=None, description="Skills acquired with experience.")
    skills_preview: Optional[StrictStr] = Field(default=None, description="Insight of the skills acquired with experience.")
    __properties: ClassVar[List[str]] = ["id", "company", "job_title", "started_on", "ended_on", "location", "description", "employment_type", "workplace_type", "skills", "skills_preview"]

    @field_validator('employment_type')
    def employment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SELF_EMPLOYED', 'CONTRACT', 'CONTRACT_PART_TIME', 'PERMANENT', 'PERMANENT_PART_TIME', 'INTERNSHIP', 'APPRENTICESHIP', 'FREELANCE', 'FREELANCE_ARTS_WORKER', 'CIVIL_SERVICE_INTERNSHIP', 'VOLUNTEERING', 'CIVIL_SERVANT', 'TEMPORARY']):
            raise ValueError("must be one of enum values ('SELF_EMPLOYED', 'CONTRACT', 'CONTRACT_PART_TIME', 'PERMANENT', 'PERMANENT_PART_TIME', 'INTERNSHIP', 'APPRENTICESHIP', 'FREELANCE', 'FREELANCE_ARTS_WORKER', 'CIVIL_SERVICE_INTERNSHIP', 'VOLUNTEERING', 'CIVIL_SERVANT', 'TEMPORARY')")
        return value

    @field_validator('workplace_type')
    def workplace_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ON_SITE', 'HYBRID', 'REMOTE']):
            raise ValueError("must be one of enum values ('ON_SITE', 'HYBRID', 'REMOTE')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PartialProfileWorkExperienceInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PartialProfileWorkExperienceInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "company": LinkedInCertificationsInnerOrganization.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "job_title": obj.get("job_title"),
            "started_on": obj.get("started_on"),
            "ended_on": obj.get("ended_on"),
            "location": obj.get("location"),
            "description": obj.get("description"),
            "employment_type": obj.get("employment_type"),
            "workplace_type": obj.get("workplace_type"),
            "skills": obj.get("skills"),
            "skills_preview": obj.get("skills_preview")
        })
        return _obj


