# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PerformClassicSearchFromUrl200ResponseAnyOf2DataInner(BaseModel):
    """
    PerformClassicSearchFromUrl200ResponseAnyOf2DataInner
    """ # noqa: E501
    object: StrictStr
    product: StrictStr
    id: StrictStr = Field(description="The ID of the user.")
    display_name: StrictStr = Field(description="The display name of the User.")
    public_identifier: Optional[StrictStr] = Field(default=None, description="The public identifier of the User.")
    profile_url: Optional[StrictStr] = Field(default=None, description="The profile URL of the User.")
    public_picture_url: Optional[StrictStr] = Field(default=None, description="The public picture URL of the User.")
    relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of relations of the User.")
    shared_relations_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of relations that you share with the User.")
    followers_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of the followers of the User.")
    location: StrictStr = Field(description="The location of the User.")
    headline: StrictStr = Field(description="The headline of the User.")
    industry: Optional[StrictStr] = Field(default=None, description="The industry to which the User belongs.")
    is_premium: Optional[StrictBool] = Field(default=None, description="Whether the User has a premium account.")
    is_verified: Optional[StrictBool] = Field(default=None, description="Whether the User has a verified account.")
    is_open_profile: Optional[StrictBool] = Field(default=None, description="Whether the User has an Open Profile. The Open Profile feature allows anyone on LinkedIn to contact a Premium member for free.")
    can_send_inmail: Optional[StrictBool] = Field(default=None, description="Whether it is possible to send an inMail to this User.")
    network_distance: StrictStr = Field(description="Network distance to a User.       `SELF`: Yourself.       `FIRST_DEGREE`: 1st degree connection.       `SECOND_DEGREE`: 2nd degree connection (connection of a 1st degree).       `THIRD_DEGREE`: 3rd degree connection (connection of a 2nd degree).       `OUT_OF_NETWORK`: Unreachable user.'")
    keywords_match: Optional[StrictStr] = Field(default=None, description="The search terms that produced this result.")
    __properties: ClassVar[List[str]] = ["object", "product", "id", "display_name", "public_identifier", "profile_url", "public_picture_url", "relations_count", "shared_relations_count", "followers_count", "location", "headline", "industry", "is_premium", "is_verified", "is_open_profile", "can_send_inmail", "network_distance", "keywords_match"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PeopleSearchResult']):
            raise ValueError("must be one of enum values ('PeopleSearchResult')")
        return value

    @field_validator('product')
    def product_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['classic']):
            raise ValueError("must be one of enum values ('classic')")
        return value

    @field_validator('network_distance')
    def network_distance_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SELF', 'FIRST_DEGREE', 'SECOND_DEGREE', 'THIRD_DEGREE', 'OUT_OF_NETWORK']):
            raise ValueError("must be one of enum values ('SELF', 'FIRST_DEGREE', 'SECOND_DEGREE', 'THIRD_DEGREE', 'OUT_OF_NETWORK')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PerformClassicSearchFromUrl200ResponseAnyOf2DataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PerformClassicSearchFromUrl200ResponseAnyOf2DataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "product": obj.get("product"),
            "id": obj.get("id"),
            "display_name": obj.get("display_name"),
            "public_identifier": obj.get("public_identifier"),
            "profile_url": obj.get("profile_url"),
            "public_picture_url": obj.get("public_picture_url"),
            "relations_count": obj.get("relations_count"),
            "shared_relations_count": obj.get("shared_relations_count"),
            "followers_count": obj.get("followers_count"),
            "location": obj.get("location"),
            "headline": obj.get("headline"),
            "industry": obj.get("industry"),
            "is_premium": obj.get("is_premium"),
            "is_verified": obj.get("is_verified"),
            "is_open_profile": obj.get("is_open_profile"),
            "can_send_inmail": obj.get("can_send_inmail"),
            "network_distance": obj.get("network_distance"),
            "keywords_match": obj.get("keywords_match")
        })
        return _obj


