# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SalesNavigatorSavedSearch(BaseModel):
    """
    SalesNavigatorSavedSearch
    """ # noqa: E501
    object: StrictStr
    product: StrictStr
    last_viewed_at: Optional[Union[StrictFloat, StrictInt]] = Field(description="The number of comments to the post. `null` if counter is hidden.")
    new_results_count: Optional[Union[StrictFloat, StrictInt]] = Field(description="The number of comments to the post. `null` if counter is hidden.")
    __properties: ClassVar[List[str]] = ["object", "product", "last_viewed_at", "new_results_count"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SavedSearchMetadata']):
            raise ValueError("must be one of enum values ('SavedSearchMetadata')")
        return value

    @field_validator('product')
    def product_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['sales_navigator']):
            raise ValueError("must be one of enum values ('sales_navigator')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SalesNavigatorSavedSearch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if last_viewed_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_viewed_at is None and "last_viewed_at" in self.model_fields_set:
            _dict['last_viewed_at'] = None

        # set to None if new_results_count (nullable) is None
        # and model_fields_set contains the field
        if self.new_results_count is None and "new_results_count" in self.model_fields_set:
            _dict['new_results_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SalesNavigatorSavedSearch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "product": obj.get("product"),
            "last_viewed_at": obj.get("last_viewed_at"),
            "new_results_count": obj.get("new_results_count")
        })
        return _obj


