# coding: utf-8

"""
    Unipile API

    Unified API for messaging, calendars, emails and socials.

    The version of the OpenAPI document: 2.44.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from unipile.models.pairing_code1 import PairingCode1
from unipile.models.qr_code1 import QRCode1
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

WHATSAPP2CREDENTIALS_ANY_OF_SCHEMAS = ["PairingCode1", "QRCode1"]

class WhatsApp2Credentials(BaseModel):
    """
    The user credentials required by the provider to authenticate with.
    """

    # data type: QRCode1
    anyof_schema_1_validator: Optional[QRCode1] = None
    # data type: PairingCode1
    anyof_schema_2_validator: Optional[PairingCode1] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[PairingCode1, QRCode1]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "PairingCode1", "QRCode1" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = WhatsApp2Credentials.model_construct()
        error_messages = []
        # validate data type: QRCode1
        if not isinstance(v, QRCode1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `QRCode1`")
        else:
            return v

        # validate data type: PairingCode1
        if not isinstance(v, PairingCode1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PairingCode1`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in WhatsApp2Credentials with anyOf schemas: PairingCode1, QRCode1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[QRCode1] = None
        try:
            instance.actual_instance = QRCode1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[PairingCode1] = None
        try:
            instance.actual_instance = PairingCode1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WhatsApp2Credentials with anyOf schemas: PairingCode1, QRCode1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], PairingCode1, QRCode1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


